import type { ArtifactTemplate } from "./types";

const lines = (v: string | string[] | undefined) =>
  Array.isArray(v) ? v.filter(Boolean).map((x) => `- ${x}`).join("\n") : v ?? "";

const s = (v: Record<string, string | string[]>, k: string) => {
  const x = v[k];
  return Array.isArray(x) ? x.join(", ") : (x ?? "");
};

export const artifactTemplates: ArtifactTemplate[] = [
  {
    id: "intake",
    name: "AI Intake Form",
    category: "Governance",
    description: "Kick off any AI request with a structured intake.",
    fields: [
      { id: "name", label: "Use case name", type: "text" },
      { id: "requester", label: "Requester + business unit", type: "text" },
      { id: "type", label: "Request type", type: "select", options: [
        "SaaS AI platform onboarding", "New feature on existing platform", "New model", "New agent", "New connector", "In-house AI app", "RAG app", "Coding assistant", "AI Lab experiment",
      ] },
      { id: "purpose", label: "Business purpose", type: "textarea" },
      { id: "data", label: "Data involved (classifications)", type: "textarea", placeholder: "PII, Confidential, Regulated…" },
      { id: "users", label: "Users and volumes", type: "text" },
      { id: "risks", label: "Known risks / concerns", type: "textarea" },
      { id: "timeline", label: "Timeline / urgency", type: "text" },
    ],
    markdown: (v) => `# AI Intake — ${s(v, "name")}\n\n_Practice artifact for learning only._\n\n**Requester:** ${s(v, "requester")}\n**Type:** ${s(v, "type")}\n**Timeline:** ${s(v, "timeline")}\n\n## Business purpose\n${s(v, "purpose")}\n\n## Data\n${s(v, "data")}\n\n## Users\n${s(v, "users")}\n\n## Known risks\n${s(v, "risks")}\n`,
  },
  {
    id: "tad",
    name: "Technical Architecture Document (TAD)",
    category: "Architecture",
    description: "High-level technical architecture.",
    fields: [
      { id: "name", label: "System name", type: "text" },
      { id: "pattern", label: "Chosen pattern", type: "select", options: ["SaaS onboarding", "In-house RAG", "Agent", "Coding assistant", "Other"] },
      { id: "components", label: "Components (one per line)", type: "textarea" },
      { id: "identity", label: "Identity flow", type: "textarea" },
      { id: "data", label: "Data flow", type: "textarea" },
      { id: "nfrs", label: "NFRs (latency, availability, cost, scale)", type: "textarea" },
      { id: "decisions", label: "Key decisions and rationale", type: "textarea" },
    ],
    markdown: (v) => `# TAD — ${s(v, "name")}\n\n_Practice artifact for learning only._\n\n**Pattern:** ${s(v, "pattern")}\n\n## Components\n${lines(v.components?.toString().split("\n"))}\n\n## Identity flow\n${s(v, "identity")}\n\n## Data flow\n${s(v, "data")}\n\n## NFRs\n${s(v, "nfrs")}\n\n## Decisions\n${s(v, "decisions")}\n`,
  },
  {
    id: "sar",
    name: "SAR Checklist",
    category: "Security",
    description: "Security Architecture Review checklist.",
    fields: [
      { id: "name", label: "System", type: "text" },
      { id: "identity", label: "Identity & access", type: "textarea" },
      { id: "network", label: "Network & endpoints", type: "textarea" },
      { id: "data", label: "Data protection", type: "textarea" },
      { id: "app", label: "App security (LLM Top 10)", type: "textarea" },
      { id: "agent", label: "Agent / tool controls", type: "textarea" },
      { id: "connector", label: "Connector scopes", type: "textarea" },
      { id: "logging", label: "Logging & detection", type: "textarea" },
      { id: "residual", label: "Residual risk", type: "textarea" },
      { id: "decision", label: "Decision", type: "select", options: ["Approve", "Conditional approve", "Block"] },
    ],
    markdown: (v) => `# SAR — ${s(v, "name")}\n\n_Practice artifact for learning only._\n\n**Decision:** ${s(v, "decision")}\n\n## Identity & access\n${s(v, "identity")}\n\n## Network & endpoints\n${s(v, "network")}\n\n## Data protection\n${s(v, "data")}\n\n## App security (LLM Top 10)\n${s(v, "app")}\n\n## Agent / tools\n${s(v, "agent")}\n\n## Connectors\n${s(v, "connector")}\n\n## Logging & detection\n${s(v, "logging")}\n\n## Residual risk\n${s(v, "residual")}\n`,
  },
  {
    id: "threat-model",
    name: "Threat Model",
    category: "Security",
    description: "STRIDE + LLM Top 10 threat model.",
    fields: [
      { id: "name", label: "System", type: "text" },
      { id: "assets", label: "Assets", type: "textarea" },
      { id: "actors", label: "Actors", type: "textarea" },
      { id: "threats", label: "Threats (STRIDE + LLM Top 10)", type: "textarea" },
      { id: "mitigations", label: "Mitigations", type: "textarea" },
    ],
    markdown: (v) => `# Threat Model — ${s(v, "name")}\n\n_Practice artifact for learning only._\n\n## Assets\n${s(v, "assets")}\n\n## Actors\n${s(v, "actors")}\n\n## Threats\n${s(v, "threats")}\n\n## Mitigations\n${s(v, "mitigations")}\n`,
  },
  {
    id: "pia",
    name: "Privacy Impact Assessment",
    category: "Privacy",
    description: "PIA checklist for AI.",
    fields: [
      { id: "name", label: "System", type: "text" },
      { id: "pii", label: "PII categories", type: "textarea" },
      { id: "basis", label: "Legal basis / consent", type: "textarea" },
      { id: "retention", label: "Retention & deletion", type: "textarea" },
      { id: "residency", label: "Residency & transfers", type: "textarea" },
      { id: "subprocessors", label: "Subprocessors", type: "textarea" },
      { id: "dsr", label: "DSR handling", type: "textarea" },
    ],
    markdown: (v) => `# PIA — ${s(v, "name")}\n\n_Practice artifact for learning only._\n\n## PII categories\n${s(v, "pii")}\n\n## Legal basis / consent\n${s(v, "basis")}\n\n## Retention & deletion\n${s(v, "retention")}\n\n## Residency & transfers\n${s(v, "residency")}\n\n## Subprocessors\n${s(v, "subprocessors")}\n\n## DSR handling\n${s(v, "dsr")}\n`,
  },
  {
    id: "legal",
    name: "Legal Review Summary",
    category: "Legal",
    description: "Vendor terms, DPA, client restrictions.",
    fields: [
      { id: "name", label: "System / vendor", type: "text" },
      { id: "terms", label: "Vendor terms highlights", type: "textarea" },
      { id: "dpa", label: "DPA status", type: "text" },
      { id: "client", label: "Client restrictions", type: "textarea" },
      { id: "ip", label: "IP / output ownership", type: "textarea" },
      { id: "regulated", label: "Regulated data considerations", type: "textarea" },
    ],
    markdown: (v) => `# Legal Review — ${s(v, "name")}\n\n_Practice artifact for learning only._\n\n**DPA:** ${s(v, "dpa")}\n\n## Vendor terms\n${s(v, "terms")}\n\n## Client restrictions\n${s(v, "client")}\n\n## IP / output ownership\n${s(v, "ip")}\n\n## Regulated data\n${s(v, "regulated")}\n`,
  },
  {
    id: "qrm",
    name: "QRM Risk Assessment",
    category: "Risk",
    description: "Inherent + residual risk with treatment.",
    fields: [
      { id: "name", label: "System", type: "text" },
      { id: "inherent", label: "Inherent risks", type: "textarea" },
      { id: "controls", label: "Controls in place", type: "textarea" },
      { id: "residual", label: "Residual risk", type: "textarea" },
      { id: "acceptance", label: "Risk acceptance (name + rationale)", type: "textarea" },
    ],
    markdown: (v) => `# QRM Risk Assessment — ${s(v, "name")}\n\n_Practice artifact for learning only._\n\n## Inherent\n${s(v, "inherent")}\n\n## Controls\n${s(v, "controls")}\n\n## Residual\n${s(v, "residual")}\n\n## Acceptance\n${s(v, "acceptance")}\n`,
  },
  {
    id: "datagov",
    name: "Data Governance Summary",
    category: "Data",
    description: "Sources, owners, classification, permission trimming, vector lifecycle.",
    fields: [
      { id: "name", label: "System", type: "text" },
      { id: "sources", label: "Data sources (one per line)", type: "textarea" },
      { id: "owners", label: "Data owner sign-offs", type: "textarea" },
      { id: "classification", label: "Classification handling", type: "textarea" },
      { id: "trimming", label: "Permission trimming approach", type: "textarea" },
      { id: "lifecycle", label: "Vector lifecycle (ingest, refresh, delete)", type: "textarea" },
    ],
    markdown: (v) => `# Data Governance — ${s(v, "name")}\n\n_Practice artifact for learning only._\n\n## Sources\n${s(v, "sources")}\n\n## Owners\n${s(v, "owners")}\n\n## Classification\n${s(v, "classification")}\n\n## Permission trimming\n${s(v, "trimming")}\n\n## Vector lifecycle\n${s(v, "lifecycle")}\n`,
  },
  {
    id: "iam",
    name: "IAM Review Summary",
    category: "IAM",
    description: "Identity, RBAC, service identities, conditional access.",
    fields: [
      { id: "name", label: "System", type: "text" },
      { id: "users", label: "User identity flow", type: "textarea" },
      { id: "service", label: "Service identity flow", type: "textarea" },
      { id: "rbac", label: "RBAC / groups", type: "textarea" },
      { id: "ca", label: "Conditional access", type: "textarea" },
    ],
    markdown: (v) => `# IAM Review — ${s(v, "name")}\n\n_Practice artifact for learning only._\n\n## User identity flow\n${s(v, "users")}\n\n## Service identity flow\n${s(v, "service")}\n\n## RBAC / groups\n${s(v, "rbac")}\n\n## Conditional access\n${s(v, "ca")}\n`,
  },
  {
    id: "devsecops",
    name: "DevSecOps Checklist",
    category: "Security",
    description: "SAST/DAST/SCA, secrets, IaC, prompt/model versioning.",
    fields: [
      { id: "name", label: "System", type: "text" },
      { id: "scans", label: "SAST / DAST / SCA results", type: "textarea" },
      { id: "secrets", label: "Secrets handling", type: "textarea" },
      { id: "iac", label: "IaC scanning", type: "textarea" },
      { id: "prompts", label: "Prompt / model versioning", type: "textarea" },
      { id: "release", label: "Release gates", type: "textarea" },
    ],
    markdown: (v) => `# DevSecOps — ${s(v, "name")}\n\n_Practice artifact for learning only._\n\n## Scans\n${s(v, "scans")}\n\n## Secrets\n${s(v, "secrets")}\n\n## IaC\n${s(v, "iac")}\n\n## Prompt / model versioning\n${s(v, "prompts")}\n\n## Release gates\n${s(v, "release")}\n`,
  },
  {
    id: "agent-gov",
    name: "Agent Governance Summary",
    category: "Agent",
    description: "Tools, identity, HITL, kill switch, audit.",
    fields: [
      { id: "name", label: "Agent", type: "text" },
      { id: "tools", label: "Tools + scopes", type: "textarea" },
      { id: "identity", label: "Identity model", type: "textarea" },
      { id: "hitl", label: "HITL policy", type: "textarea" },
      { id: "kill", label: "Kill switch", type: "textarea" },
      { id: "audit", label: "Audit / detection", type: "textarea" },
    ],
    markdown: (v) => `# Agent Governance — ${s(v, "name")}\n\n_Practice artifact for learning only._\n\n## Tools\n${s(v, "tools")}\n\n## Identity\n${s(v, "identity")}\n\n## HITL\n${s(v, "hitl")}\n\n## Kill switch\n${s(v, "kill")}\n\n## Audit\n${s(v, "audit")}\n`,
  },
  {
    id: "connector-gov",
    name: "Connector Governance Summary",
    category: "Connector",
    description: "Scopes, credentials, DLP, lifecycle.",
    fields: [
      { id: "name", label: "Connector", type: "text" },
      { id: "scopes", label: "OAuth scopes", type: "textarea" },
      { id: "creds", label: "Credential storage", type: "textarea" },
      { id: "dlp", label: "DLP coverage", type: "textarea" },
      { id: "lifecycle", label: "Lifecycle (review cadence)", type: "textarea" },
    ],
    markdown: (v) => `# Connector Governance — ${s(v, "name")}\n\n_Practice artifact for learning only._\n\n## Scopes\n${s(v, "scopes")}\n\n## Credentials\n${s(v, "creds")}\n\n## DLP\n${s(v, "dlp")}\n\n## Lifecycle\n${s(v, "lifecycle")}\n`,
  },
  {
    id: "runbook",
    name: "Support Runbook",
    category: "Ops",
    description: "On-call runbook for the AI app.",
    fields: [
      { id: "name", label: "System", type: "text" },
      { id: "sev", label: "Severity matrix", type: "textarea" },
      { id: "alerts", label: "Alerts + responders", type: "textarea" },
      { id: "kill", label: "Kill switch procedure", type: "textarea" },
      { id: "escalation", label: "Escalation path", type: "textarea" },
    ],
    markdown: (v) => `# Runbook — ${s(v, "name")}\n\n_Practice artifact for learning only._\n\n## Severity\n${s(v, "sev")}\n\n## Alerts\n${s(v, "alerts")}\n\n## Kill switch\n${s(v, "kill")}\n\n## Escalation\n${s(v, "escalation")}\n`,
  },
  {
    id: "training",
    name: "Training Plan",
    category: "Adoption",
    description: "Enablement plan for users, admins, developers.",
    fields: [
      { id: "name", label: "Platform / app", type: "text" },
      { id: "audiences", label: "Audiences", type: "textarea" },
      { id: "modules", label: "Modules", type: "textarea" },
      { id: "aup", label: "Acceptable-use highlights", type: "textarea" },
    ],
    markdown: (v) => `# Training Plan — ${s(v, "name")}\n\n_Practice artifact for learning only._\n\n## Audiences\n${s(v, "audiences")}\n\n## Modules\n${s(v, "modules")}\n\n## Acceptable use\n${s(v, "aup")}\n`,
  },
  {
    id: "gonogo",
    name: "Go / No-Go Summary",
    category: "Governance",
    description: "Final go/no-go with pre-reqs and residual risk.",
    fields: [
      { id: "name", label: "System", type: "text" },
      { id: "decision", label: "Decision", type: "select", options: ["Go", "Conditional Go", "No-Go"] },
      { id: "prereqs", label: "Pre-reqs before go-live", type: "textarea" },
      { id: "residual", label: "Residual risk + owner", type: "textarea" },
      { id: "sponsors", label: "Sponsors sign-off", type: "textarea" },
    ],
    markdown: (v) => `# Go / No-Go — ${s(v, "name")}\n\n_Practice artifact for learning only._\n\n**Decision:** ${s(v, "decision")}\n\n## Pre-reqs\n${s(v, "prereqs")}\n\n## Residual risk\n${s(v, "residual")}\n\n## Sponsors\n${s(v, "sponsors")}\n`,
  },
];

export const artifactsById: Record<string, ArtifactTemplate> = Object.fromEntries(
  artifactTemplates.map((a) => [a.id, a]),
);