import type { ExamDef } from "./types";

export const exams: ExamDef[] = [
  {
    id: "security-architect",
    name: "AI Security Architect — Practice Exam",
    roleId: "security-architect",
    description: "10 questions across OWASP LLM Top 10, agents, connectors, RAG, and Zero Trust.",
    depth: "deep",
    questions: [
      {
        id: "sa-1",
        type: "find-risk",
        prompt: "A RAG app concatenates retrieved documents into the system prompt. Biggest risk?",
        options: [
          { id: "a", label: "Cost" },
          { id: "b", label: "Indirect prompt injection escalating to tool misuse", correct: true },
          { id: "c", label: "Latency" },
          { id: "d", label: "Model hallucination" },
        ],
        explanation: "Retrieved content is untrusted input. Concatenating it into the system prompt gives it authority.",
        domain: "security",
      },
      {
        id: "sa-2",
        type: "choose-control",
        prompt: "Best control against agent tool misuse via prompt injection?",
        options: [
          { id: "a", label: "Instruct the model to refuse malicious inputs" },
          { id: "b", label: "Strict tool allowlist + per-tool schemas + HITL for state-changing tools", correct: true },
          { id: "c", label: "Bigger model" },
          { id: "d", label: "Rate limiting" },
        ],
        explanation: "Constrain what the model can do — you cannot rely on it to constrain itself.",
        domain: "security",
      },
      {
        id: "sa-3",
        type: "gate",
        prompt: "Public model endpoint for an in-house RAG app in production.",
        options: [
          { id: "a", label: "Go" },
          { id: "b", label: "Conditional — WAF" },
          { id: "c", label: "No-Go — private endpoint required", correct: true },
          { id: "d", label: "Defer" },
        ],
        explanation: "Baseline Zero Trust for enterprise AI.",
        domain: "security",
      },
      {
        id: "sa-4",
        type: "mc",
        prompt: "OWASP LLM Top 10 category most relevant to a poisoned SharePoint doc?",
        options: [
          { id: "a", label: "Prompt Injection", correct: true },
          { id: "b", label: "Insecure Output Handling" },
          { id: "c", label: "Model DoS" },
          { id: "d", label: "Model Theft" },
        ],
        explanation: "Indirect prompt injection is a form of prompt injection (LLM01).",
        domain: "security",
      },
      {
        id: "sa-5",
        type: "find-risk",
        prompt: "Agent uses a shared service account with full Jira permissions.",
        options: [
          { id: "a", label: "Latency" },
          { id: "b", label: "Bypass of per-user permissions + huge blast radius", correct: true },
          { id: "c", label: "Cost" },
          { id: "d", label: "Cache misses" },
        ],
        explanation: "Shared service accounts erase user-level accountability and permission scoping.",
        domain: "security",
      },
      {
        id: "sa-6",
        type: "owner",
        prompt: "Who owns SAR sign-off for an in-house AI app?",
        options: [
          { id: "a", label: "Platform Admin" },
          { id: "b", label: "AI Security Architect", correct: true },
          { id: "c", label: "Product Manager" },
          { id: "d", label: "Legal" },
        ],
        explanation: "Security Architecture Review is owned by AI Security Architecture, partnered with Solution Architecture.",
        domain: "governance_grc",
      },
      {
        id: "sa-7",
        type: "choose-control",
        prompt: "Best control for secrets ending up in coding-assistant context?",
        options: [
          { id: "a", label: "User training only" },
          { id: "b", label: "Repo-level secrets scanning + pre-commit hooks + policy-blocked file types", correct: true },
          { id: "c", label: "Bigger context window" },
          { id: "d", label: "Turn the assistant off" },
        ],
        explanation: "Defense in the SDLC pipeline, not at the human layer.",
        domain: "security",
      },
      {
        id: "sa-8",
        type: "mc",
        prompt: "Kill switch counts as a control only if…",
        options: [
          { id: "a", label: "It exists in Confluence" },
          { id: "b", label: "It has been tested in the last 30 days with logged evidence", correct: true },
          { id: "c", label: "The vendor supports it" },
          { id: "d", label: "It has a red button icon" },
        ],
        explanation: "Untested controls do not exist in an audit.",
        domain: "security",
      },
      {
        id: "sa-9",
        type: "find-risk",
        prompt: "AI Search index for a RAG app has no security-trimming filter.",
        options: [
          { id: "a", label: "Latency" },
          { id: "b", label: "Any authenticated user can retrieve any indexed document", correct: true },
          { id: "c", label: "Model refuses to answer" },
          { id: "d", label: "Cost" },
        ],
        explanation: "The index becomes a permission-bypass side channel.",
        domain: "security",
      },
      {
        id: "sa-10",
        type: "gate",
        prompt: "A vendor connector requires 'Sites.FullControl.All' but only reads one library.",
        options: [
          { id: "a", label: "Go" },
          { id: "b", label: "Conditional — pilot only" },
          { id: "c", label: "No-Go — push back for narrower scope; block until reduced", correct: true },
          { id: "d", label: "Defer" },
        ],
        explanation: "Broad scope requests are the top connector risk. Block or narrow.",
        domain: "security",
      },
    ],
  },
  {
    id: "platform-admin",
    name: "AI Platform Admin — Practice Exam (Sample)",
    roleId: "platform-admin",
    description: "Sample exam. Expand with more questions as you learn.",
    depth: "scaffold",
    questions: [
      {
        id: "pa-1",
        type: "mc",
        prompt: "Best single control to eliminate personal-account shadow AI?",
        options: [
          { id: "a", label: "Acceptable-use policy" },
          { id: "b", label: "Verified domain / domain capture on the enterprise workspace", correct: true },
          { id: "c", label: "Block ChatGPT at proxy" },
          { id: "d", label: "Longer passwords" },
        ],
        explanation: "Domain capture forces employees with corporate email into the managed workspace.",
        domain: "platform",
      },
    ],
  },
  {
    id: "governance-operator",
    name: "AI Governance Operator — Practice Exam (Sample)",
    roleId: "governance-operator",
    description: "Sample exam.",
    depth: "scaffold",
    questions: [
      {
        id: "go-1",
        type: "owner",
        prompt: "A team wants a new SharePoint-grounded RAG assistant. Which review path is REQUIRED?",
        options: [
          { id: "a", label: "Security only" },
          { id: "b", label: "Security + Privacy + Legal + QRM + Data Governance + IAM", correct: true },
          { id: "c", label: "Governance committee only" },
          { id: "d", label: "None" },
        ],
        explanation: "RAG on internal data touches every review domain.",
        domain: "governance_grc",
      },
    ],
  },
  {
    id: "solution-architect",
    name: "AI Solution Architect — Practice Exam (Sample)",
    roleId: "solution-architect",
    description: "Sample exam.",
    depth: "scaffold",
    questions: [
      {
        id: "arch-1",
        type: "mc",
        prompt: "You are asked to add a chatbot to help find HR policies. Best pattern?",
        options: [
          { id: "a", label: "Fine-tuned model on policies" },
          { id: "b", label: "Permission-aware RAG with citations", correct: true },
          { id: "c", label: "An agent with 5 tools" },
          { id: "d", label: "A search box" },
        ],
        explanation: "RAG with citations is the standard pattern for grounded Q&A over enterprise content.",
        domain: "architecture",
      },
    ],
  },
  {
    id: "grc-lead",
    name: "Enterprise AI GRC Lead — Practice Exam (Sample)",
    roleId: "grc-lead",
    description: "Sample exam.",
    depth: "scaffold",
    questions: [
      {
        id: "grc-1",
        type: "gate",
        prompt: "A business unit proposes a fourth chat AI platform 'to compare.' You already have three.",
        options: [
          { id: "a", label: "Go" },
          { id: "b", label: "Conditional — 30-day AI Lab bake-off, retire one before adding", correct: true },
          { id: "c", label: "No-Go — reject" },
          { id: "d", label: "Defer" },
        ],
        explanation: "Rationalize platforms; do not accumulate.",
        domain: "governance_grc",
      },
    ],
  },
];

export const examsById: Record<string, ExamDef> = Object.fromEntries(exams.map((e) => [e.id, e]));