import type { RoleDef } from "./types";

export const roles: RoleDef[] = [
  {
    id: "platform-admin",
    order: 1,
    name: "AI Platform Admin",
    short: "Operates enterprise AI platforms safely.",
    mission:
      "Own the day-to-day administration of enterprise AI platforms (Copilot, ChatGPT Enterprise, Gemini, Claude, Replit, Codex) — identity, RBAC, features, connectors, logging, cost, and lifecycle.",
    owns: [
      "Tenant / workspace configuration",
      "SSO, SAML, OIDC, SCIM",
      "RBAC and admin roles",
      "Feature flags and rollout rings",
      "Plugin / connector enablement",
      "Audit logs and usage analytics",
      "License and seat allocation",
      "Offboarding of AI-owned assets",
    ],
    daily: [
      "Review new access requests and admin tickets",
      "Check audit logs for anomalies",
      "Approve or deny plugin/connector enablement",
      "Monitor token / seat / cost dashboards",
      "Handle release notes and feature toggles",
      "Coordinate with security on incidents",
    ],
    meetings: [
      "Weekly AI platform stand-up",
      "Change advisory board (CAB)",
      "Vendor roadmap briefings",
      "Security & governance sync",
      "Enablement/adoption review",
    ],
    documents: [
      "Admin runbook per platform",
      "Feature rollout plan",
      "Access review report",
      "Offboarding checklist",
      "Audit log inspection log",
    ],
    questions: [
      "Who owns this workspace?",
      "Is SSO + SCIM enforced?",
      "What features are default-on vs opt-in?",
      "Which connectors are enabled and by whom?",
      "Where do logs go and who reads them?",
      "What breaks when a user leaves?",
    ],
    risks: [
      "Shadow workspaces created outside IT",
      "SSO bypass via personal accounts",
      "Over-permissive admin roles",
      "Default-on features that leak data (training, plugins, memory)",
      "Connectors granted org-wide scopes",
      "Orphaned agents / GPTs after offboarding",
    ],
    tools: [
      "M365 admin center + Copilot admin",
      "ChatGPT Enterprise Compliance API",
      "Gemini / Google Workspace admin",
      "Claude Console",
      "Entra ID / Okta",
      "SIEM (Splunk, Sentinel)",
    ],
    technicalSkills: [
      "SAML/OIDC/SCIM configuration",
      "RBAC and group design",
      "Audit log parsing",
      "API-based admin (Graph, Compliance)",
      "Cost telemetry",
    ],
    governanceSkills: [
      "Feature-approval routing",
      "Access recertification",
      "Acceptable-use enforcement",
    ],
    securitySkills: [
      "Least privilege for admin roles",
      "Log source hardening",
      "Connector scope review",
    ],
    artifacts: [
      "Admin runbook",
      "Access review report",
      "Offboarding checklist",
      "Feature enablement decision record",
    ],
    coach: [
      "Before enabling a feature, ask: 'If every user turns this on tomorrow, what data leaves the boundary?'",
      "Every admin role added is a blast radius — prefer scoped groups over global admin.",
      "Logs you can't query in <5 minutes during an incident are not really logs.",
      "Offboarding isn't done until agents, GPTs, connectors, and API keys owned by the user are transferred or revoked.",
    ],
    masteryDomains: ["platform", "ops", "governance_grc"],
    labIds: ["saas-onboarding", "connector"],
    scenarioIds: ["sc-chatgpt-onboarding", "sc-offboarding-agent-owner"],
    platformIds: ["m365-copilot", "chatgpt-enterprise", "gemini-enterprise", "claude-enterprise"],
    stages: {
      beginner: ["Understand SSO/SCIM/RBAC basics", "Read admin runbooks"],
      intermediate: ["Configure a workspace end-to-end", "Handle offboarding"],
      advanced: ["Design multi-platform admin operating model", "Automate access review"],
      expert: ["Own admin standards across 5+ AI platforms with audit-ready evidence"],
    },
  },
  {
    id: "governance-operator",
    order: 2,
    name: "AI Enablement / Governance Operator",
    short: "Moves AI requests through intake, registry, and approval.",
    mission:
      "Run the AI intake, registry, risk tiering, and pilot-to-production workflow. Route requests to the right reviewers and collect evidence.",
    owns: [
      "AI intake queue",
      "AI registry / inventory",
      "Use-case classification",
      "Risk tiering",
      "Approval routing",
      "Evidence collection",
      "Recertification and retirement",
      "Exception register and expiry tracking",
      "Recertification cycle for live AI systems",
    ],
    daily: [
      "Triage new intake submissions",
      "Assign risk tier and reviewers",
      "Chase evidence from teams",
      "Update registry status",
      "Prep governance committee packet",
      "Chase evidence that reviewers have asked for",
      "Close out decisions and update the registry",
    ],
    meetings: [
      "AI governance committee",
      "Intake triage",
      "Pilot readiness review",
      "Retirement / decommission review",
      "Weekly intake triage",
      "Quarterly recertification review",
    ],
    documents: [
      "Intake form",
      "Registry entry",
      "Risk-tier decision",
      "Governance committee packet",
      "Recertification report",
      "Exception record with expiry",
      "Decommissioning checklist",
    ],
    questions: [
      "Is this a new platform, feature, model, agent, connector, RAG app, or coding tool?",
      "Which reviewers are required for this class?",
      "What risk tier applies?",
      "What evidence is missing?",
      "Can this be approved for sandbox only?",
      "Has this data source got a named owner?",
      "What happens to this system when its sponsor leaves?",
    ],
    risks: [
      "Missing intake for shadow AI",
      "Wrong risk tier leading to skipped reviews",
      "Approvals without evidence",
      "Registry drift from reality",
      "Shadow AI adopted outside intake entirely",
      "Exceptions that quietly become permanent",
    ],
    tools: [
      "ServiceNow / Jira",
      "SharePoint / Confluence",
      "Registry spreadsheet or GRC tool",
      "AI system registry",
      "Evidence repository",
    ],
    technicalSkills: ["Workflow design", "Metadata modeling"],
    governanceSkills: ["Risk tiering", "Approval routing", "Evidence management"],
    securitySkills: ["Recognize when SAR is required", "Recognize connector risks"],
    artifacts: ["Intake form", "Registry entry", "Governance decision record"],
    coach: [
      "Every 'quick pilot' request needs a registry entry — no exceptions.",
      "Risk tier drives review path; get it wrong and either you over-govern or you miss a real risk.",
      "An exception without an expiry date is just a policy change nobody agreed to.",
      "If you cannot say who owns a data source, you cannot approve its use — that is the whole job.",
    ],
    masteryDomains: ["governance_grc", "ops"],
    labIds: ["privacy", "legal", "qrm", "data-governance"],
    scenarioIds: ["sc-rag-sharepoint", "sc-copilot-studio-hr"],
    platformIds: ["copilot-studio", "chatgpt-enterprise"],
    stages: {
      beginner: ["Classify request types", "Populate registry"],
      intermediate: ["Route to correct reviewers", "Manage evidence"],
      advanced: ["Design governance workflow", "Handle exceptions"],
      expert: ["Run committee, defend decisions to executives"],
    },
  },
  {
    id: "solution-architect",
    order: 3,
    name: "AI Solution Architecture Analyst",
    short: "Designs enterprise AI systems technically.",
    mission:
      "Translate business needs into concrete architecture — SaaS vs in-house, RAG, agents, connectors, identity propagation, environments, and NFRs.",
    owns: [
      "Technical Architecture Document (TAD)",
      "Solution Design Document (SDD)",
      "Data flow and sequence diagrams",
      "Model and pattern selection",
      "Environment strategy",
      "Non-functional requirements: latency, cost and failure behaviour",
      "Environment promotion path from lab to production",
    ],
    daily: [
      "Whiteboard architectures",
      "Review vendor patterns",
      "Pair with security and data teams",
      "Refine NFRs and SLOs",
      "Review designs against the trust-boundary checklist",
      "Model cost and latency for proposed changes",
    ],
    meetings: [
      "Architecture review board",
      "Design workshops",
      "SAR partnership",
      "Architecture review board",
      "Design pairing with security architecture",
    ],
    documents: [
      "TAD",
      "SDD",
      "Reference architecture",
      "Pattern library entry",
      "Technical architecture document",
      "Environment promotion plan",
    ],
    questions: [
      "Build, buy, configure, or extend?",
      "Does RAG solve the problem or is fine-tuning right?",
      "How does user identity propagate to retrieval?",
      "What is the blast radius on failure?",
      "Where exactly is authorisation enforced?",
      "What does this do when the model provider is slow or down?",
    ],
    risks: [
      "Choosing agents where a workflow would do",
      "RAG without permission trimming",
      "Single-region single-model designs",
      "Ignoring latency and cost NFRs",
      "Authorisation enforced in the client rather than the server",
      "No fallback when the provider degrades",
    ],
    tools: [
      "Azure AI Foundry",
      "Vertex AI",
      "AWS Bedrock",
      "Miro / Lucid",
      "Evaluation harness",
      "Load and cost testing",
    ],
    technicalSkills: ["RAG design", "Agent design", "Identity propagation", "API integration"],
    governanceSkills: ["Pattern rationalization"],
    securitySkills: ["Threat-informed design"],
    artifacts: ["TAD", "SDD", "DFD narrative"],
    coach: [
      "The best architecture is the one your on-call can debug at 2 AM.",
      "Draw the identity flow before you draw the prompt flow.",
      "Draw the trust boundary first. Most AI design arguments are really arguments about where it sits.",
      "If the design has no answer for provider latency or outage, it is a prototype, not an architecture.",
    ],
    masteryDomains: ["architecture", "agent_rag_connector"],
    labIds: ["rag", "agent", "in-house-app", "ai-engineering"],
    scenarioIds: ["sc-rag-sharepoint", "sc-bedrock-case-assistant"],
    platformIds: [
      "azure-ai-foundry",
      "vertex-ai",
      "aws-bedrock",
      "internal-ai-apps",
      "rag-systems",
      "ai-agents",
    ],
    stages: {
      beginner: ["Read reference patterns"],
      intermediate: ["Produce a TAD for a RAG app"],
      advanced: ["Design multi-agent systems with HITL"],
      expert: ["Own the enterprise AI pattern library"],
    },
  },
  {
    id: "security-architect",
    order: 4,
    name: "AI Security Architecture Partner",
    short: "Secures AI apps, platforms, agents, RAG, connectors, and coding tools.",
    mission:
      "Threat-model and control every AI system. Own SAR, OWASP LLM Top 10, MITRE ATLAS, connector scopes, agent action boundaries, and secrets hygiene.",
    owns: [
      "Security Architecture Review (SAR)",
      "Threat models",
      "Control catalog (OWASP LLM Top 10, MITRE ATLAS)",
      "Kill-switch and HITL requirements",
      "Secrets and identity boundary reviews",
    ],
    daily: [
      "Threat-model incoming designs",
      "Review connector scopes",
      "Chase remediation evidence",
      "Pair with detection engineering",
    ],
    meetings: ["SAR intake", "AppSec sync", "Red team debrief", "Governance committee"],
    documents: ["SAR report", "Threat model", "Control mapping", "Residual risk memo"],
    questions: [
      "Who is the user and how do they authenticate?",
      "What can the AI see and what can it do?",
      "What can an attacker manipulate?",
      "What can leak?",
      "How do we detect abuse and stop it?",
    ],
    risks: [
      "Prompt injection (direct + indirect)",
      "RAG poisoning",
      "Overprivileged agent tools",
      "Connector scope creep",
      "Secrets in prompts / code assist context",
      "Data exfiltration via model outputs",
    ],
    tools: [
      "OWASP LLM Top 10",
      "MITRE ATLAS",
      "SAST/DAST/SCA",
      "Container/IaC scanners",
      "Cloud CSPM",
      "SIEM/SOAR",
    ],
    technicalSkills: [
      "Threat modeling",
      "OAuth scopes and identity design",
      "Egress and network controls",
      "Prompt injection defense patterns",
    ],
    governanceSkills: ["SAR governance", "Residual risk articulation"],
    securitySkills: ["OWASP LLM Top 10", "MITRE ATLAS", "Kill-switch design", "HITL patterns"],
    artifacts: ["SAR report", "Threat model", "Control mapping"],
    coach: [
      "Assume every retrieved document contains attacker instructions.",
      "Every tool an agent can call is a permission you granted an attacker on a bad day.",
      "No kill switch, no production.",
    ],
    masteryDomains: ["security", "agent_rag_connector"],
    labIds: ["agent", "connector", "zero-trust", "devsecops", "rag"],
    scenarioIds: ["sc-prompt-injection-rag", "sc-agent-overprivilege"],
    platformIds: ["azure-ai-foundry", "chatgpt-enterprise", "claude-code", "codex"],
    stages: {
      beginner: ["Learn OWASP LLM Top 10"],
      intermediate: ["Threat-model a RAG app"],
      advanced: ["Design agent action boundaries and HITL"],
      expert: ["Own the AI security control catalog for the enterprise"],
    },
  },
  {
    id: "grc-lead",
    order: 5,
    name: "Enterprise AI Architect / AI GRC Lead",
    short: "Leads enterprise AI strategy, governance, risk, and lifecycle.",
    mission:
      "Own the enterprise AI operating model — strategy, portfolio, platform rationalization, governance framework, risk tiers, AI Lab operating model, FinOps, adoption, executive reporting.",
    owns: [
      "AI operating model",
      "Governance framework",
      "Portfolio strategy",
      "Executive dashboards",
      "Policy and standards",
      "AI Lab charter",
      "Risk appetite statement for AI adoption",
      "Board and committee reporting on AI risk",
    ],
    daily: [
      "Executive briefings",
      "Portfolio review",
      "Policy exception decisions",
      "Cross-functional escalations",
      "Review incoming risk acceptances against appetite",
      "Track control testing results and overdue remediation",
    ],
    meetings: [
      "Exec steering",
      "AI governance committee",
      "Risk & audit committee",
      "Risk committee",
      "Regulatory horizon scanning",
    ],
    documents: [
      "AI strategy",
      "Operating model",
      "Policy",
      "Standards",
      "Board packet",
      "Risk appetite statement",
      "Control testing report",
    ],
    questions: [
      "Should we allow this at all?",
      "Does this duplicate an existing platform?",
      "Who accepts residual risk?",
      "What should executives see?",
      "Who is authorised to accept this level of exposure?",
      "Which regulatory obligation does this control actually satisfy?",
    ],
    risks: [
      "Platform sprawl",
      "Ungoverned AI Lab spillover",
      "Missing exec visibility on residual risk",
      "Adoption stalls without support model",
      "Acceptance recorded by someone without the authority to give it",
      "Controls documented but never tested",
    ],
    tools: [
      "GRC platform",
      "Executive dashboards",
      "Policy library",
      "GRC platform",
      "Regulatory mapping matrix",
    ],
    technicalSkills: ["Systems thinking", "Reference architecture literacy"],
    governanceSkills: ["Operating model design", "Policy authoring", "Committee facilitation"],
    securitySkills: ["Risk articulation to executives"],
    artifacts: ["Operating model", "Policy", "Roadmap", "Board packet"],
    coach: [
      "Rationalize platforms before you scale — three AI tools chosen well beat ten chosen fast.",
      "The exec dashboard is the operating model made visible.",
      "Residual risk with no named acceptor is unowned risk, and it always surfaces during an incident.",
      "A control that has never been tested is a claim, not a control.",
    ],
    masteryDomains: ["governance_grc", "architecture", "ops"],
    labIds: ["qrm", "privacy", "legal"],
    scenarioIds: ["sc-exec-three-tools"],
    platformIds: ["m365-copilot", "chatgpt-enterprise", "claude-code"],
    stages: {
      beginner: ["Understand governance domains"],
      intermediate: ["Design a single control area end-to-end"],
      advanced: ["Author the operating model"],
      expert: ["Lead enterprise AI strategy and governance"],
    },
  },
];

export const rolesById: Record<string, RoleDef> = Object.fromEntries(roles.map((r) => [r.id, r]));
