import type { RoleDef } from "./types";

export const roles: RoleDef[] = [
  {
    id: "platform-admin",
    order: 1,
    name: "AI Platform Admin",
    short: "Operates enterprise AI platforms safely.",
    mission:
      "Own the day-to-day administration of enterprise AI platforms (Copilot, ChatGPT Enterprise, Gemini, Claude, Replit, Codex) — identity, RBAC, features, connectors, logging, cost, and lifecycle.",
    owns: [
      "Tenant / workspace configuration",
      "SSO, SAML, OIDC, SCIM",
      "RBAC and admin roles",
      "Feature flags and rollout rings",
      "Plugin / connector enablement",
      "Audit logs and usage analytics",
      "License and seat allocation",
      "Offboarding of AI-owned assets",
    ],
    daily: [
      "Review new access requests and admin tickets",
      "Check audit logs for anomalies",
      "Approve or deny plugin/connector enablement",
      "Monitor token / seat / cost dashboards",
      "Handle release notes and feature toggles",
      "Coordinate with security on incidents",
    ],
    meetings: [
      "Weekly AI platform stand-up",
      "Change advisory board (CAB)",
      "Vendor roadmap briefings",
      "Security & governance sync",
      "Enablement/adoption review",
    ],
    documents: [
      "Admin runbook per platform",
      "Feature rollout plan",
      "Access review report",
      "Offboarding checklist",
      "Audit log inspection log",
    ],
    questions: [
      "Who owns this workspace?",
      "Is SSO + SCIM enforced?",
      "What features are default-on vs opt-in?",
      "Which connectors are enabled and by whom?",
      "Where do logs go and who reads them?",
      "What breaks when a user leaves?",
    ],
    risks: [
      "Shadow workspaces created outside IT",
      "SSO bypass via personal accounts",
      "Over-permissive admin roles",
      "Default-on features that leak data (training, plugins, memory)",
      "Connectors granted org-wide scopes",
      "Orphaned agents / GPTs after offboarding",
    ],
    tools: [
      "M365 admin center + Copilot admin",
      "ChatGPT Enterprise Compliance API",
      "Gemini / Google Workspace admin",
      "Claude Console",
      "Entra ID / Okta",
      "SIEM (Splunk, Sentinel)",
    ],
    technicalSkills: [
      "SAML/OIDC/SCIM configuration",
      "RBAC and group design",
      "Audit log parsing",
      "API-based admin (Graph, Compliance)",
      "Cost telemetry",
    ],
    governanceSkills: [
      "Feature-approval routing",
      "Access recertification",
      "Acceptable-use enforcement",
    ],
    securitySkills: [
      "Least privilege for admin roles",
      "Log source hardening",
      "Connector scope review",
    ],
    artifacts: [
      "Admin runbook",
      "Access review report",
      "Offboarding checklist",
      "Feature enablement decision record",
    ],
    coach: [
      "Before enabling a feature, ask: 'If every user turns this on tomorrow, what data leaves the boundary?'",
      "Every admin role added is a blast radius — prefer scoped groups over global admin.",
      "Logs you can't query in <5 minutes during an incident are not really logs.",
      "Offboarding isn't done until agents, GPTs, connectors, and API keys owned by the user are transferred or revoked.",
    ],
    masteryDomains: ["platform", "ops", "governance_grc"],
    labIds: ["saas-onboarding", "connector", "iam", "ai-operations"],
    scenarioIds: [
      "sc-chatgpt-onboarding",
      "sc-offboarding-agent-owner",
      "sc-exec-three-tools",
      "sc-agent-overprivilege",
    ],
    platformIds: ["m365-copilot", "chatgpt-enterprise", "gemini-enterprise", "claude-enterprise"],
    stages: {
      beginner: [
        "Action licence and access requests correctly, and know which need judgement",
        "Find a setting in the admin console without being told where it is",
        "Explain to a user why a connector was not approved",
      ],
      intermediate: [
        "Own the configuration baseline and defend each choice in a review",
        "Wire identity end to end, including deactivation for leavers",
        "Read the bill and say which workload caused a change",
        "Run a pilot cohort and expand on evidence rather than enthusiasm",
      ],
      advanced: [
        "Design the connector review route so it is used rather than avoided",
        "Get audit logs into your own retention and prove they are complete",
        "Reclaim unused licences and show the saving",
        "Hold a control against a senior exception request, with an alternative",
      ],
      expert: [
        "Set the standard other administrators follow",
        "Be consulted by security and privacy before policy is written, not after",
        "Run a multi-tenant or multi-product estate without the baselines drifting apart",
        "Own the commercial relationship with the vendor on technical terms",
      ],
    },
  },
  {
    id: "governance-operator",
    order: 2,
    name: "AI Enablement / Governance Operator",
    short: "Moves AI requests through intake, registry, and approval.",
    mission:
      "Run the AI intake, registry, risk tiering, and pilot-to-production workflow. Route requests to the right reviewers and collect evidence.",
    owns: [
      "AI intake queue",
      "AI registry / inventory",
      "Use-case classification",
      "Risk tiering",
      "Approval routing",
      "Evidence collection",
      "Recertification and retirement",
      "Exception register and expiry tracking",
      "Recertification cycle for live AI systems",
    ],
    daily: [
      "Triage new intake submissions",
      "Assign risk tier and reviewers",
      "Chase evidence from teams",
      "Update registry status",
      "Prep governance committee packet",
      "Chase evidence that reviewers have asked for",
      "Close out decisions and update the registry",
    ],
    meetings: [
      "AI governance committee",
      "Intake triage",
      "Pilot readiness review",
      "Retirement / decommission review",
      "Weekly intake triage",
      "Quarterly recertification review",
    ],
    documents: [
      "Intake form",
      "Registry entry",
      "Risk-tier decision",
      "Governance committee packet",
      "Recertification report",
      "Exception record with expiry",
      "Decommissioning checklist",
    ],
    questions: [
      "Is this a new platform, feature, model, agent, connector, RAG app, or coding tool?",
      "Which reviewers are required for this class?",
      "What risk tier applies?",
      "What evidence is missing?",
      "Can this be approved for sandbox only?",
      "Has this data source got a named owner?",
      "What happens to this system when its sponsor leaves?",
    ],
    risks: [
      "Missing intake for shadow AI",
      "Wrong risk tier leading to skipped reviews",
      "Approvals without evidence",
      "Registry drift from reality",
      "Shadow AI adopted outside intake entirely",
      "Exceptions that quietly become permanent",
    ],
    tools: [
      "ServiceNow / Jira",
      "SharePoint / Confluence",
      "Registry spreadsheet or GRC tool",
      "AI system registry",
      "Evidence repository",
    ],
    technicalSkills: ["Workflow design", "Metadata modeling"],
    governanceSkills: ["Risk tiering", "Approval routing", "Evidence management"],
    securitySkills: ["Recognize when SAR is required", "Recognize connector risks"],
    artifacts: ["Intake form", "Registry entry", "Governance decision record"],
    coach: [
      "Every 'quick pilot' request needs a registry entry — no exceptions.",
      "Risk tier drives review path; get it wrong and either you over-govern or you miss a real risk.",
      "An exception without an expiry date is just a policy change nobody agreed to.",
      "If you cannot say who owns a data source, you cannot approve its use — that is the whole job.",
    ],
    masteryDomains: ["governance_grc", "ops"],
    labIds: ["privacy", "legal", "qrm", "data-governance"],
    scenarioIds: [
      "sc-copilot-studio-hr",
      "sc-rag-sharepoint",
      "sc-exec-three-tools",
      "sc-chatgpt-onboarding",
    ],
    platformIds: ["copilot-studio", "chatgpt-enterprise"],
    stages: {
      beginner: [
        "Run intake accurately and keep the register true",
        "Recognise which use cases need more than the baseline",
        "Chase a referral until it is answered rather than logged",
      ],
      intermediate: [
        "Tier independently and defend the tier to the requesting team",
        "Produce a pack that is complete before it reaches a board",
        "Spot the question a submission has quietly left open",
        "Turn a vague request into an assessable description",
      ],
      advanced: [
        "Design intake so it takes minutes and teams stop routing around it",
        "Run a review meeting to a decision rather than to another meeting",
        "Reduce autonomy as an alternative to blocking, and argue it",
        "Track exceptions to expiry and reopen them",
      ],
      expert: [
        "Own the framework, and change it when it stops fitting",
        "Be the person teams come to before building, because it is faster",
        "Report to an executive audience without losing the substance",
        "Bring a regulator's expectation into the process before it is mandatory",
      ],
    },
  },
  {
    id: "solution-architect",
    order: 3,
    name: "AI Solution Architecture Analyst",
    short: "Designs enterprise AI systems technically.",
    mission:
      "Translate business needs into concrete architecture — SaaS vs in-house, RAG, agents, connectors, identity propagation, environments, and NFRs.",
    owns: [
      "Technical Architecture Document (TAD)",
      "Solution Design Document (SDD)",
      "Data flow and sequence diagrams",
      "Model and pattern selection",
      "Environment strategy",
      "Non-functional requirements: latency, cost and failure behaviour",
      "Environment promotion path from lab to production",
    ],
    daily: [
      "Whiteboard architectures",
      "Review vendor patterns",
      "Pair with security and data teams",
      "Refine NFRs and SLOs",
      "Review designs against the trust-boundary checklist",
      "Model cost and latency for proposed changes",
    ],
    meetings: [
      "Architecture review board",
      "Design workshops",
      "SAR partnership",
      "Vendor and platform selection reviews",
      "Design pairing with security architecture",
    ],
    documents: [
      "TAD",
      "SDD",
      "Reference architecture",
      "Pattern library entry",
      "Technical architecture document",
      "Environment promotion plan",
    ],
    questions: [
      "Build, buy, configure, or extend?",
      "Does RAG solve the problem or is fine-tuning right?",
      "How does user identity propagate to retrieval?",
      "What is the blast radius on failure?",
      "Where exactly is authorisation enforced?",
      "What does this do when the model provider is slow or down?",
    ],
    risks: [
      "Choosing agents where a workflow would do",
      "RAG without permission trimming",
      "Single-region single-model designs",
      "Ignoring latency and cost NFRs",
      "Authorisation enforced in the client rather than the server",
      "No fallback when the provider degrades",
    ],
    tools: [
      "Azure AI Foundry",
      "Vertex AI",
      "AWS Bedrock",
      "Miro / Lucid",
      "Evaluation harness",
      "Load and cost testing",
    ],
    technicalSkills: ["RAG design", "Agent design", "Identity propagation", "API integration"],
    governanceSkills: ["Pattern rationalization"],
    securitySkills: ["Threat-informed design"],
    artifacts: ["TAD", "SDD", "DFD narrative"],
    coach: [
      "The best architecture is the one your on-call can debug at 2 AM.",
      "Draw the identity flow before you draw the prompt flow.",
      "Draw the trust boundary first. Most AI design arguments are really arguments about where it sits.",
      "If the design has no answer for provider latency or outage, it is a prototype, not an architecture.",
    ],
    masteryDomains: ["architecture", "agent_rag_connector"],
    labIds: ["rag", "agent", "in-house-app", "ai-engineering", "ai-evaluation"],
    scenarioIds: [
      "sc-rag-sharepoint",
      "sc-bedrock-case-assistant",
      "sc-prompt-injection-rag",
      "sc-copilot-studio-hr",
    ],
    platformIds: [
      "azure-ai-foundry",
      "vertex-ai",
      "aws-bedrock",
      "internal-ai-apps",
      "rag-systems",
      "ai-agents",
    ],
    stages: {
      beginner: [
        "Read the reference patterns and be able to redraw one from memory",
        "Explain where authorisation happens in a retrieval system, and whose it is",
        "Follow an existing design without needing it re-explained",
      ],
      intermediate: [
        "Produce a technical architecture document for a retrieval application",
        "Build an evaluation set and establish a baseline before tuning anything",
        "Choose a model on measured task performance and cost rather than on rank",
        "Defend a design in review, and change it when the challenge is right",
      ],
      advanced: [
        "Design multi-agent systems with human oversight on the irreversible paths",
        "Make the system fail without taking the product down: timeouts, bulkheads, degraded mode",
        "Make any decision reconstructable months later — prompt version, sources, pinned model",
        "Halve cost per resolved query without losing measured quality",
      ],
      expert: [
        "Own the enterprise AI pattern library other teams build from",
        "Say what should not be built, and be listened to",
        "Set the evaluation approach the organisation measures everything against",
        "Take a design through regulatory or client scrutiny and have it hold",
      ],
    },
  },
  {
    id: "security-architect",
    order: 4,
    name: "AI Security Architecture Partner",
    short: "Secures AI apps, platforms, agents, RAG, connectors, and coding tools.",
    mission:
      "Threat-model and control every AI system. Own SAR, OWASP LLM Top 10, MITRE ATLAS, connector scopes, agent action boundaries, and secrets hygiene.",
    owns: [
      "Security Architecture Review (SAR)",
      "Threat models",
      "Control catalog (OWASP LLM Top 10, MITRE ATLAS)",
      "Kill-switch and HITL requirements",
      "Secrets and identity boundary reviews",
    ],
    daily: [
      "Threat-model incoming designs",
      "Review connector scopes",
      "Chase remediation evidence",
      "Pair with detection engineering",
    ],
    meetings: ["SAR intake", "AppSec sync", "Red team debrief", "Governance committee"],
    documents: ["SAR report", "Threat model", "Control mapping", "Residual risk memo"],
    questions: [
      "Who is the user and how do they authenticate?",
      "What can the AI see and what can it do?",
      "What can an attacker manipulate?",
      "What can leak?",
      "How do we detect abuse and stop it?",
    ],
    risks: [
      "Prompt injection (direct + indirect)",
      "RAG poisoning",
      "Overprivileged agent tools",
      "Connector scope creep",
      "Secrets in prompts / code assist context",
      "Data exfiltration via model outputs",
    ],
    tools: [
      "OWASP LLM Top 10",
      "MITRE ATLAS",
      "SAST/DAST/SCA",
      "Container/IaC scanners",
      "Cloud CSPM",
      "SIEM/SOAR",
    ],
    technicalSkills: [
      "Threat modeling",
      "OAuth scopes and identity design",
      "Egress and network controls",
      "Prompt injection defense patterns",
    ],
    governanceSkills: ["SAR governance", "Residual risk articulation"],
    securitySkills: ["OWASP LLM Top 10", "MITRE ATLAS", "Kill-switch design", "HITL patterns"],
    artifacts: ["SAR report", "Threat model", "Control mapping"],
    coach: [
      "Assume every retrieved document contains attacker instructions.",
      "Every tool an agent can call is a permission you granted an attacker on a bad day.",
      "No kill switch, no production.",
    ],
    masteryDomains: ["security", "agent_rag_connector"],
    labIds: ["agent", "connector", "zero-trust", "devsecops", "rag", "iam"],
    scenarioIds: [
      "sc-prompt-injection-rag",
      "sc-agent-overprivilege",
      "sc-rag-sharepoint",
      "sc-offboarding-agent-owner",
    ],
    platformIds: ["azure-ai-foundry", "chatgpt-enterprise", "claude-code", "codex"],
    stages: {
      beginner: [
        "Run a review against a checklist and know which answers need escalating",
        "Name the common LLM risk classes and give a real mitigation for each",
        "Trace one request end to end and write down which identity touches what",
      ],
      intermediate: [
        "Threat model a system you have never seen, live, and defend the findings",
        "Tell the difference between a control and a compensating disclaimer",
        "Distinguish where a risk is concentrated from where it is merely present",
        "Write findings engineers act on rather than argue with",
      ],
      advanced: [
        "Contain a compromised agent and reason about blast radius under pressure",
        "Design the trust boundary between retrieved content and tool authority",
        "Negotiate what blocks a launch and what becomes a verifiable condition",
        "Know when a condition cannot be verified in time, and say so",
      ],
      expert: [
        "Change how systems get built, because teams design differently knowing what you ask",
        "Set the review standard other architects apply",
        "Hold a position against commercial pressure and keep the relationship",
        "Be the person the board asks when something has gone wrong",
      ],
    },
  },
  {
    id: "grc-lead",
    order: 5,
    name: "Enterprise AI Architect / AI GRC Lead",
    short: "Leads enterprise AI strategy, governance, risk, and lifecycle.",
    mission:
      "Own the enterprise AI operating model — strategy, portfolio, platform rationalization, governance framework, risk tiers, AI Lab operating model, FinOps, adoption, executive reporting.",
    owns: [
      "AI operating model",
      "Governance framework",
      "Portfolio strategy",
      "Executive dashboards",
      "Policy and standards",
      "AI Lab charter",
      "Risk appetite statement for AI adoption",
      "Board and committee reporting on AI risk",
    ],
    daily: [
      "Executive briefings",
      "Portfolio review",
      "Policy exception decisions",
      "Cross-functional escalations",
      "Review incoming risk acceptances against appetite",
      "Track control testing results and overdue remediation",
    ],
    meetings: [
      "Exec steering",
      "AI governance committee",
      "Risk & audit committee",
      "Risk committee",
      "Regulatory horizon scanning",
    ],
    documents: [
      "AI strategy",
      "Operating model",
      "Policy",
      "Standards",
      "Board packet",
      "Risk appetite statement",
      "Control testing report",
    ],
    questions: [
      "Should we allow this at all?",
      "Does this duplicate an existing platform?",
      "Who accepts residual risk?",
      "What should executives see?",
      "Who is authorised to accept this level of exposure?",
      "Which regulatory obligation does this control actually satisfy?",
    ],
    risks: [
      "Platform sprawl",
      "Ungoverned AI Lab spillover",
      "Missing exec visibility on residual risk",
      "Adoption stalls without support model",
      "Acceptance recorded by someone without the authority to give it",
      "Controls documented but never tested",
    ],
    tools: [
      "GRC platform",
      "Executive dashboards",
      "Policy library",
      "Evidence repository",
      "Regulatory mapping matrix",
    ],
    technicalSkills: ["Systems thinking", "Reference architecture literacy"],
    governanceSkills: ["Operating model design", "Policy authoring", "Committee facilitation"],
    securitySkills: ["Risk articulation to executives"],
    artifacts: ["Operating model", "Policy", "Roadmap", "Board packet"],
    coach: [
      "Rationalize platforms before you scale — three AI tools chosen well beat ten chosen fast.",
      "The exec dashboard is the operating model made visible.",
      "Residual risk with no named acceptor is unowned risk, and it always surfaces during an incident.",
      "A control that has never been tested is a claim, not a control.",
    ],
    masteryDomains: ["governance_grc", "architecture", "ops"],
    labIds: ["qrm", "privacy", "legal"],
    scenarioIds: [
      "sc-exec-three-tools",
      "sc-copilot-studio-hr",
      "sc-bedrock-case-assistant",
      "sc-chatgpt-onboarding",
    ],
    platformIds: ["m365-copilot", "chatgpt-enterprise", "claude-code"],
    stages: {
      beginner: [
        "Run assurance against an existing framework and report reliably",
        "Tell evidence that a control operated from evidence that it merely exists",
        "Keep the register true, including the systems nobody declared",
      ],
      intermediate: [
        "Tier by harm and autonomy, and defend the tiering to the business",
        "Decide what evidence is sufficient, and say why, in writing",
        "Run an approval route people use because it is faster than avoiding it",
        "Close a long-open referral rather than logging it again",
      ],
      advanced: [
        "Design the assurance framework and defend it to a regulator",
        "Set expiry and material-change triggers so no acceptance becomes permanent",
        "Report honestly to a board, including what is not yet known",
        "Concede a fair challenge without losing the position that matters",
      ],
      expert: [
        "Set risk appetite for AI where no baseline exists",
        "Translate incoming regulation into what has to change here, before it is mandatory",
        "Be accountable when it goes publicly wrong",
        "Build a function the business brings problems to early",
      ],
    },
  },
];

export const rolesById: Record<string, RoleDef> = Object.fromEntries(roles.map((r) => [r.id, r]));
