/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppArtifactsRouteImport } from './routes/app.artifacts'
import { Route as AppCareerPathRouteImport } from './routes/app.career-path'
import { Route as AppCompetenciesRouteImport } from './routes/app.competencies'
import { Route as AppExamsRouteImport } from './routes/app.exams'
import { Route as AppFlashcardsRouteImport } from './routes/app.flashcards'
import { Route as AppLabEngineRouteImport } from './routes/app.lab-engine'
import { Route as AppMyRunsRouteImport } from './routes/app.my-runs'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as SiteForAudienceRouteImport } from './routes/_site.for.$audience'
import { Route as SitePathsIndexRouteImport } from './routes/_site.paths.index'
import { Route as SitePathsPathIdRouteImport } from './routes/_site.paths.$pathId'
import { Route as AppArtifactsArtifactIdRouteImport } from './routes/app.artifacts.$artifactId'
import { Route as AppExamsExamIdRouteImport } from './routes/app.exams.$examId'
import { Route as AppLabEngineLabIdRouteImport } from './routes/app.lab-engine.$labId'
import { Route as AppLabsLabIdRouteImport } from './routes/app.labs.$labId'
import { Route as AppLearnPlatformRouteImport } from './routes/app.learn.platform'
import { Route as AppLearnRoleRouteImport } from './routes/app.learn.role'
import { Route as AppLearnScenarioRouteImport } from './routes/app.learn.scenario'
import { Route as AppMyRunsRunIdRouteImport } from './routes/app.my-runs.$runId'
import { Route as AppPlatformsPlatformIdRouteImport } from './routes/app.platforms.$platformId'
import { Route as AppRolesRoleIdRouteImport } from './routes/app.roles.$roleId'
import { Route as AppScenariosScenarioIdRouteImport } from './routes/app.scenarios.$scenarioId'
import { Route as AppScenariosRagTicketAgentRouteImport } from './routes/app.scenarios.rag-ticket-agent'
import { Route as AppSimulatorsEnvRouteImport } from './routes/app.simulators.env'
import { Route as AppSimulatorsInHouseAppRouteImport } from './routes/app.simulators.in-house-app'
import { Route as AppSimulatorsSaasOnboardingRouteImport } from './routes/app.simulators.saas-onboarding'
import { Route as AppSimulatorsGoNoGoIndexRouteImport } from './routes/app.simulators.go-no-go.index'
import { Route as AppSimulatorsGoNoGoCaseIdRouteImport } from './routes/app.simulators.go-no-go.$caseId'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppArtifactsRoute = AppArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerPathRoute = AppCareerPathRouteImport.update({
  id: '/career-path',
  path: '/career-path',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetenciesRoute = AppCompetenciesRouteImport.update({
  id: '/competencies',
  path: '/competencies',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsRoute = AppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsRoute = AppFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppRoute,
} as any)
const AppLabEngineRoute = AppLabEngineRouteImport.update({
  id: '/lab-engine',
  path: '/lab-engine',
  getParentRoute: () => AppRoute,
} as any)
const AppMyRunsRoute = AppMyRunsRouteImport.update({
  id: '/my-runs',
  path: '/my-runs',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const SiteForAudienceRoute = SiteForAudienceRouteImport.update({
  id: '/for/$audience',
  path: '/for/$audience',
  getParentRoute: () => SiteRoute,
} as any)
const SitePathsIndexRoute = SitePathsIndexRouteImport.update({
  id: '/paths/',
  path: '/paths/',
  getParentRoute: () => SiteRoute,
} as any)
const SitePathsPathIdRoute = SitePathsPathIdRouteImport.update({
  id: '/paths/$pathId',
  path: '/paths/$pathId',
  getParentRoute: () => SiteRoute,
} as any)
const AppArtifactsArtifactIdRoute = AppArtifactsArtifactIdRouteImport.update({
  id: '/$artifactId',
  path: '/$artifactId',
  getParentRoute: () => AppArtifactsRoute,
} as any)
const AppExamsExamIdRoute = AppExamsExamIdRouteImport.update({
  id: '/$examId',
  path: '/$examId',
  getParentRoute: () => AppExamsRoute,
} as any)
const AppLabEngineLabIdRoute = AppLabEngineLabIdRouteImport.update({
  id: '/$labId',
  path: '/$labId',
  getParentRoute: () => AppLabEngineRoute,
} as any)
const AppLabsLabIdRoute = AppLabsLabIdRouteImport.update({
  id: '/labs/$labId',
  path: '/labs/$labId',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnPlatformRoute = AppLearnPlatformRouteImport.update({
  id: '/learn/platform',
  path: '/learn/platform',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoleRoute = AppLearnRoleRouteImport.update({
  id: '/learn/role',
  path: '/learn/role',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnScenarioRoute = AppLearnScenarioRouteImport.update({
  id: '/learn/scenario',
  path: '/learn/scenario',
  getParentRoute: () => AppRoute,
} as any)
const AppMyRunsRunIdRoute = AppMyRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => AppMyRunsRoute,
} as any)
const AppPlatformsPlatformIdRoute = AppPlatformsPlatformIdRouteImport.update({
  id: '/platforms/$platformId',
  path: '/platforms/$platformId',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoleIdRoute = AppRolesRoleIdRouteImport.update({
  id: '/roles/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosScenarioIdRoute = AppScenariosScenarioIdRouteImport.update({
  id: '/scenarios/$scenarioId',
  path: '/scenarios/$scenarioId',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosRagTicketAgentRoute =
  AppScenariosRagTicketAgentRouteImport.update({
    id: '/scenarios/rag-ticket-agent',
    path: '/scenarios/rag-ticket-agent',
    getParentRoute: () => AppRoute,
  } as any)
const AppSimulatorsEnvRoute = AppSimulatorsEnvRouteImport.update({
  id: '/simulators/env',
  path: '/simulators/env',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulatorsInHouseAppRoute = AppSimulatorsInHouseAppRouteImport.update({
  id: '/simulators/in-house-app',
  path: '/simulators/in-house-app',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulatorsSaasOnboardingRoute =
  AppSimulatorsSaasOnboardingRouteImport.update({
    id: '/simulators/saas-onboarding',
    path: '/simulators/saas-onboarding',
    getParentRoute: () => AppRoute,
  } as any)
const AppSimulatorsGoNoGoIndexRoute =
  AppSimulatorsGoNoGoIndexRouteImport.update({
    id: '/simulators/go-no-go/',
    path: '/simulators/go-no-go/',
    getParentRoute: () => AppRoute,
  } as any)
const AppSimulatorsGoNoGoCaseIdRoute =
  AppSimulatorsGoNoGoCaseIdRouteImport.update({
    id: '/simulators/go-no-go/$caseId',
    path: '/simulators/go-no-go/$caseId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/about': typeof SiteAboutRoute
  '/app/artifacts': typeof AppArtifactsRouteWithChildren
  '/app/career-path': typeof AppCareerPathRoute
  '/app/competencies': typeof AppCompetenciesRoute
  '/app/exams': typeof AppExamsRouteWithChildren
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/lab-engine': typeof AppLabEngineRouteWithChildren
  '/app/my-runs': typeof AppMyRunsRouteWithChildren
  '/app/notes': typeof AppNotesRoute
  '/app/': typeof AppIndexRoute
  '/for/$audience': typeof SiteForAudienceRoute
  '/paths/$pathId': typeof SitePathsPathIdRoute
  '/app/artifacts/$artifactId': typeof AppArtifactsArtifactIdRoute
  '/app/exams/$examId': typeof AppExamsExamIdRoute
  '/app/lab-engine/$labId': typeof AppLabEngineLabIdRoute
  '/app/labs/$labId': typeof AppLabsLabIdRoute
  '/app/learn/platform': typeof AppLearnPlatformRoute
  '/app/learn/role': typeof AppLearnRoleRoute
  '/app/learn/scenario': typeof AppLearnScenarioRoute
  '/app/my-runs/$runId': typeof AppMyRunsRunIdRoute
  '/app/platforms/$platformId': typeof AppPlatformsPlatformIdRoute
  '/app/roles/$roleId': typeof AppRolesRoleIdRoute
  '/app/scenarios/$scenarioId': typeof AppScenariosScenarioIdRoute
  '/app/scenarios/rag-ticket-agent': typeof AppScenariosRagTicketAgentRoute
  '/app/simulators/env': typeof AppSimulatorsEnvRoute
  '/app/simulators/in-house-app': typeof AppSimulatorsInHouseAppRoute
  '/app/simulators/saas-onboarding': typeof AppSimulatorsSaasOnboardingRoute
  '/paths/': typeof SitePathsIndexRoute
  '/app/simulators/go-no-go/$caseId': typeof AppSimulatorsGoNoGoCaseIdRoute
  '/app/simulators/go-no-go/': typeof AppSimulatorsGoNoGoIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/about': typeof SiteAboutRoute
  '/app/artifacts': typeof AppArtifactsRouteWithChildren
  '/app/career-path': typeof AppCareerPathRoute
  '/app/competencies': typeof AppCompetenciesRoute
  '/app/exams': typeof AppExamsRouteWithChildren
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/lab-engine': typeof AppLabEngineRouteWithChildren
  '/app/my-runs': typeof AppMyRunsRouteWithChildren
  '/app/notes': typeof AppNotesRoute
  '/': typeof SiteIndexRoute
  '/app': typeof AppIndexRoute
  '/for/$audience': typeof SiteForAudienceRoute
  '/paths/$pathId': typeof SitePathsPathIdRoute
  '/app/artifacts/$artifactId': typeof AppArtifactsArtifactIdRoute
  '/app/exams/$examId': typeof AppExamsExamIdRoute
  '/app/lab-engine/$labId': typeof AppLabEngineLabIdRoute
  '/app/labs/$labId': typeof AppLabsLabIdRoute
  '/app/learn/platform': typeof AppLearnPlatformRoute
  '/app/learn/role': typeof AppLearnRoleRoute
  '/app/learn/scenario': typeof AppLearnScenarioRoute
  '/app/my-runs/$runId': typeof AppMyRunsRunIdRoute
  '/app/platforms/$platformId': typeof AppPlatformsPlatformIdRoute
  '/app/roles/$roleId': typeof AppRolesRoleIdRoute
  '/app/scenarios/$scenarioId': typeof AppScenariosScenarioIdRoute
  '/app/scenarios/rag-ticket-agent': typeof AppScenariosRagTicketAgentRoute
  '/app/simulators/env': typeof AppSimulatorsEnvRoute
  '/app/simulators/in-house-app': typeof AppSimulatorsInHouseAppRoute
  '/app/simulators/saas-onboarding': typeof AppSimulatorsSaasOnboardingRoute
  '/paths': typeof SitePathsIndexRoute
  '/app/simulators/go-no-go/$caseId': typeof AppSimulatorsGoNoGoCaseIdRoute
  '/app/simulators/go-no-go': typeof AppSimulatorsGoNoGoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_site/about': typeof SiteAboutRoute
  '/app/artifacts': typeof AppArtifactsRouteWithChildren
  '/app/career-path': typeof AppCareerPathRoute
  '/app/competencies': typeof AppCompetenciesRoute
  '/app/exams': typeof AppExamsRouteWithChildren
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/lab-engine': typeof AppLabEngineRouteWithChildren
  '/app/my-runs': typeof AppMyRunsRouteWithChildren
  '/app/notes': typeof AppNotesRoute
  '/_site/': typeof SiteIndexRoute
  '/app/': typeof AppIndexRoute
  '/_site/for/$audience': typeof SiteForAudienceRoute
  '/_site/paths/$pathId': typeof SitePathsPathIdRoute
  '/app/artifacts/$artifactId': typeof AppArtifactsArtifactIdRoute
  '/app/exams/$examId': typeof AppExamsExamIdRoute
  '/app/lab-engine/$labId': typeof AppLabEngineLabIdRoute
  '/app/labs/$labId': typeof AppLabsLabIdRoute
  '/app/learn/platform': typeof AppLearnPlatformRoute
  '/app/learn/role': typeof AppLearnRoleRoute
  '/app/learn/scenario': typeof AppLearnScenarioRoute
  '/app/my-runs/$runId': typeof AppMyRunsRunIdRoute
  '/app/platforms/$platformId': typeof AppPlatformsPlatformIdRoute
  '/app/roles/$roleId': typeof AppRolesRoleIdRoute
  '/app/scenarios/$scenarioId': typeof AppScenariosScenarioIdRoute
  '/app/scenarios/rag-ticket-agent': typeof AppScenariosRagTicketAgentRoute
  '/app/simulators/env': typeof AppSimulatorsEnvRoute
  '/app/simulators/in-house-app': typeof AppSimulatorsInHouseAppRoute
  '/app/simulators/saas-onboarding': typeof AppSimulatorsSaasOnboardingRoute
  '/_site/paths/': typeof SitePathsIndexRoute
  '/app/simulators/go-no-go/$caseId': typeof AppSimulatorsGoNoGoCaseIdRoute
  '/app/simulators/go-no-go/': typeof AppSimulatorsGoNoGoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/about'
    | '/app/artifacts'
    | '/app/career-path'
    | '/app/competencies'
    | '/app/exams'
    | '/app/flashcards'
    | '/app/lab-engine'
    | '/app/my-runs'
    | '/app/notes'
    | '/app/'
    | '/for/$audience'
    | '/paths/$pathId'
    | '/app/artifacts/$artifactId'
    | '/app/exams/$examId'
    | '/app/lab-engine/$labId'
    | '/app/labs/$labId'
    | '/app/learn/platform'
    | '/app/learn/role'
    | '/app/learn/scenario'
    | '/app/my-runs/$runId'
    | '/app/platforms/$platformId'
    | '/app/roles/$roleId'
    | '/app/scenarios/$scenarioId'
    | '/app/scenarios/rag-ticket-agent'
    | '/app/simulators/env'
    | '/app/simulators/in-house-app'
    | '/app/simulators/saas-onboarding'
    | '/paths/'
    | '/app/simulators/go-no-go/$caseId'
    | '/app/simulators/go-no-go/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/about'
    | '/app/artifacts'
    | '/app/career-path'
    | '/app/competencies'
    | '/app/exams'
    | '/app/flashcards'
    | '/app/lab-engine'
    | '/app/my-runs'
    | '/app/notes'
    | '/'
    | '/app'
    | '/for/$audience'
    | '/paths/$pathId'
    | '/app/artifacts/$artifactId'
    | '/app/exams/$examId'
    | '/app/lab-engine/$labId'
    | '/app/labs/$labId'
    | '/app/learn/platform'
    | '/app/learn/role'
    | '/app/learn/scenario'
    | '/app/my-runs/$runId'
    | '/app/platforms/$platformId'
    | '/app/roles/$roleId'
    | '/app/scenarios/$scenarioId'
    | '/app/scenarios/rag-ticket-agent'
    | '/app/simulators/env'
    | '/app/simulators/in-house-app'
    | '/app/simulators/saas-onboarding'
    | '/paths'
    | '/app/simulators/go-no-go/$caseId'
    | '/app/simulators/go-no-go'
  id:
    | '__root__'
    | '/_site'
    | '/app'
    | '/auth'
    | '/_site/about'
    | '/app/artifacts'
    | '/app/career-path'
    | '/app/competencies'
    | '/app/exams'
    | '/app/flashcards'
    | '/app/lab-engine'
    | '/app/my-runs'
    | '/app/notes'
    | '/_site/'
    | '/app/'
    | '/_site/for/$audience'
    | '/_site/paths/$pathId'
    | '/app/artifacts/$artifactId'
    | '/app/exams/$examId'
    | '/app/lab-engine/$labId'
    | '/app/labs/$labId'
    | '/app/learn/platform'
    | '/app/learn/role'
    | '/app/learn/scenario'
    | '/app/my-runs/$runId'
    | '/app/platforms/$platformId'
    | '/app/roles/$roleId'
    | '/app/scenarios/$scenarioId'
    | '/app/scenarios/rag-ticket-agent'
    | '/app/simulators/env'
    | '/app/simulators/in-house-app'
    | '/app/simulators/saas-onboarding'
    | '/_site/paths/'
    | '/app/simulators/go-no-go/$caseId'
    | '/app/simulators/go-no-go/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/artifacts': {
      id: '/app/artifacts'
      path: '/artifacts'
      fullPath: '/app/artifacts'
      preLoaderRoute: typeof AppArtifactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/career-path': {
      id: '/app/career-path'
      path: '/career-path'
      fullPath: '/app/career-path'
      preLoaderRoute: typeof AppCareerPathRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competencies': {
      id: '/app/competencies'
      path: '/competencies'
      fullPath: '/app/competencies'
      preLoaderRoute: typeof AppCompetenciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exams': {
      id: '/app/exams'
      path: '/exams'
      fullPath: '/app/exams'
      preLoaderRoute: typeof AppExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flashcards': {
      id: '/app/flashcards'
      path: '/flashcards'
      fullPath: '/app/flashcards'
      preLoaderRoute: typeof AppFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lab-engine': {
      id: '/app/lab-engine'
      path: '/lab-engine'
      fullPath: '/app/lab-engine'
      preLoaderRoute: typeof AppLabEngineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-runs': {
      id: '/app/my-runs'
      path: '/my-runs'
      fullPath: '/app/my-runs'
      preLoaderRoute: typeof AppMyRunsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_site/for/$audience': {
      id: '/_site/for/$audience'
      path: '/for/$audience'
      fullPath: '/for/$audience'
      preLoaderRoute: typeof SiteForAudienceRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/paths/': {
      id: '/_site/paths/'
      path: '/paths'
      fullPath: '/paths/'
      preLoaderRoute: typeof SitePathsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/paths/$pathId': {
      id: '/_site/paths/$pathId'
      path: '/paths/$pathId'
      fullPath: '/paths/$pathId'
      preLoaderRoute: typeof SitePathsPathIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/app/artifacts/$artifactId': {
      id: '/app/artifacts/$artifactId'
      path: '/$artifactId'
      fullPath: '/app/artifacts/$artifactId'
      preLoaderRoute: typeof AppArtifactsArtifactIdRouteImport
      parentRoute: typeof AppArtifactsRoute
    }
    '/app/exams/$examId': {
      id: '/app/exams/$examId'
      path: '/$examId'
      fullPath: '/app/exams/$examId'
      preLoaderRoute: typeof AppExamsExamIdRouteImport
      parentRoute: typeof AppExamsRoute
    }
    '/app/lab-engine/$labId': {
      id: '/app/lab-engine/$labId'
      path: '/$labId'
      fullPath: '/app/lab-engine/$labId'
      preLoaderRoute: typeof AppLabEngineLabIdRouteImport
      parentRoute: typeof AppLabEngineRoute
    }
    '/app/labs/$labId': {
      id: '/app/labs/$labId'
      path: '/labs/$labId'
      fullPath: '/app/labs/$labId'
      preLoaderRoute: typeof AppLabsLabIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learn/platform': {
      id: '/app/learn/platform'
      path: '/learn/platform'
      fullPath: '/app/learn/platform'
      preLoaderRoute: typeof AppLearnPlatformRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learn/role': {
      id: '/app/learn/role'
      path: '/learn/role'
      fullPath: '/app/learn/role'
      preLoaderRoute: typeof AppLearnRoleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learn/scenario': {
      id: '/app/learn/scenario'
      path: '/learn/scenario'
      fullPath: '/app/learn/scenario'
      preLoaderRoute: typeof AppLearnScenarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-runs/$runId': {
      id: '/app/my-runs/$runId'
      path: '/$runId'
      fullPath: '/app/my-runs/$runId'
      preLoaderRoute: typeof AppMyRunsRunIdRouteImport
      parentRoute: typeof AppMyRunsRoute
    }
    '/app/platforms/$platformId': {
      id: '/app/platforms/$platformId'
      path: '/platforms/$platformId'
      fullPath: '/app/platforms/$platformId'
      preLoaderRoute: typeof AppPlatformsPlatformIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles/$roleId': {
      id: '/app/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/app/roles/$roleId'
      preLoaderRoute: typeof AppRolesRoleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scenarios/$scenarioId': {
      id: '/app/scenarios/$scenarioId'
      path: '/scenarios/$scenarioId'
      fullPath: '/app/scenarios/$scenarioId'
      preLoaderRoute: typeof AppScenariosScenarioIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scenarios/rag-ticket-agent': {
      id: '/app/scenarios/rag-ticket-agent'
      path: '/scenarios/rag-ticket-agent'
      fullPath: '/app/scenarios/rag-ticket-agent'
      preLoaderRoute: typeof AppScenariosRagTicketAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulators/env': {
      id: '/app/simulators/env'
      path: '/simulators/env'
      fullPath: '/app/simulators/env'
      preLoaderRoute: typeof AppSimulatorsEnvRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulators/in-house-app': {
      id: '/app/simulators/in-house-app'
      path: '/simulators/in-house-app'
      fullPath: '/app/simulators/in-house-app'
      preLoaderRoute: typeof AppSimulatorsInHouseAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulators/saas-onboarding': {
      id: '/app/simulators/saas-onboarding'
      path: '/simulators/saas-onboarding'
      fullPath: '/app/simulators/saas-onboarding'
      preLoaderRoute: typeof AppSimulatorsSaasOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulators/go-no-go/': {
      id: '/app/simulators/go-no-go/'
      path: '/simulators/go-no-go'
      fullPath: '/app/simulators/go-no-go/'
      preLoaderRoute: typeof AppSimulatorsGoNoGoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulators/go-no-go/$caseId': {
      id: '/app/simulators/go-no-go/$caseId'
      path: '/simulators/go-no-go/$caseId'
      fullPath: '/app/simulators/go-no-go/$caseId'
      preLoaderRoute: typeof AppSimulatorsGoNoGoCaseIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteForAudienceRoute: typeof SiteForAudienceRoute
  SitePathsPathIdRoute: typeof SitePathsPathIdRoute
  SitePathsIndexRoute: typeof SitePathsIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteForAudienceRoute: SiteForAudienceRoute,
  SitePathsPathIdRoute: SitePathsPathIdRoute,
  SitePathsIndexRoute: SitePathsIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AppArtifactsRouteChildren {
  AppArtifactsArtifactIdRoute: typeof AppArtifactsArtifactIdRoute
}

const AppArtifactsRouteChildren: AppArtifactsRouteChildren = {
  AppArtifactsArtifactIdRoute: AppArtifactsArtifactIdRoute,
}

const AppArtifactsRouteWithChildren = AppArtifactsRoute._addFileChildren(
  AppArtifactsRouteChildren,
)

interface AppExamsRouteChildren {
  AppExamsExamIdRoute: typeof AppExamsExamIdRoute
}

const AppExamsRouteChildren: AppExamsRouteChildren = {
  AppExamsExamIdRoute: AppExamsExamIdRoute,
}

const AppExamsRouteWithChildren = AppExamsRoute._addFileChildren(
  AppExamsRouteChildren,
)

interface AppLabEngineRouteChildren {
  AppLabEngineLabIdRoute: typeof AppLabEngineLabIdRoute
}

const AppLabEngineRouteChildren: AppLabEngineRouteChildren = {
  AppLabEngineLabIdRoute: AppLabEngineLabIdRoute,
}

const AppLabEngineRouteWithChildren = AppLabEngineRoute._addFileChildren(
  AppLabEngineRouteChildren,
)

interface AppMyRunsRouteChildren {
  AppMyRunsRunIdRoute: typeof AppMyRunsRunIdRoute
}

const AppMyRunsRouteChildren: AppMyRunsRouteChildren = {
  AppMyRunsRunIdRoute: AppMyRunsRunIdRoute,
}

const AppMyRunsRouteWithChildren = AppMyRunsRoute._addFileChildren(
  AppMyRunsRouteChildren,
)

interface AppRouteChildren {
  AppArtifactsRoute: typeof AppArtifactsRouteWithChildren
  AppCareerPathRoute: typeof AppCareerPathRoute
  AppCompetenciesRoute: typeof AppCompetenciesRoute
  AppExamsRoute: typeof AppExamsRouteWithChildren
  AppFlashcardsRoute: typeof AppFlashcardsRoute
  AppLabEngineRoute: typeof AppLabEngineRouteWithChildren
  AppMyRunsRoute: typeof AppMyRunsRouteWithChildren
  AppNotesRoute: typeof AppNotesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLabsLabIdRoute: typeof AppLabsLabIdRoute
  AppLearnPlatformRoute: typeof AppLearnPlatformRoute
  AppLearnRoleRoute: typeof AppLearnRoleRoute
  AppLearnScenarioRoute: typeof AppLearnScenarioRoute
  AppPlatformsPlatformIdRoute: typeof AppPlatformsPlatformIdRoute
  AppRolesRoleIdRoute: typeof AppRolesRoleIdRoute
  AppScenariosScenarioIdRoute: typeof AppScenariosScenarioIdRoute
  AppScenariosRagTicketAgentRoute: typeof AppScenariosRagTicketAgentRoute
  AppSimulatorsEnvRoute: typeof AppSimulatorsEnvRoute
  AppSimulatorsInHouseAppRoute: typeof AppSimulatorsInHouseAppRoute
  AppSimulatorsSaasOnboardingRoute: typeof AppSimulatorsSaasOnboardingRoute
  AppSimulatorsGoNoGoCaseIdRoute: typeof AppSimulatorsGoNoGoCaseIdRoute
  AppSimulatorsGoNoGoIndexRoute: typeof AppSimulatorsGoNoGoIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArtifactsRoute: AppArtifactsRouteWithChildren,
  AppCareerPathRoute: AppCareerPathRoute,
  AppCompetenciesRoute: AppCompetenciesRoute,
  AppExamsRoute: AppExamsRouteWithChildren,
  AppFlashcardsRoute: AppFlashcardsRoute,
  AppLabEngineRoute: AppLabEngineRouteWithChildren,
  AppMyRunsRoute: AppMyRunsRouteWithChildren,
  AppNotesRoute: AppNotesRoute,
  AppIndexRoute: AppIndexRoute,
  AppLabsLabIdRoute: AppLabsLabIdRoute,
  AppLearnPlatformRoute: AppLearnPlatformRoute,
  AppLearnRoleRoute: AppLearnRoleRoute,
  AppLearnScenarioRoute: AppLearnScenarioRoute,
  AppPlatformsPlatformIdRoute: AppPlatformsPlatformIdRoute,
  AppRolesRoleIdRoute: AppRolesRoleIdRoute,
  AppScenariosScenarioIdRoute: AppScenariosScenarioIdRoute,
  AppScenariosRagTicketAgentRoute: AppScenariosRagTicketAgentRoute,
  AppSimulatorsEnvRoute: AppSimulatorsEnvRoute,
  AppSimulatorsInHouseAppRoute: AppSimulatorsInHouseAppRoute,
  AppSimulatorsSaasOnboardingRoute: AppSimulatorsSaasOnboardingRoute,
  AppSimulatorsGoNoGoCaseIdRoute: AppSimulatorsGoNoGoCaseIdRoute,
  AppSimulatorsGoNoGoIndexRoute: AppSimulatorsGoNoGoIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
