/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareerPathRouteImport } from './routes/career-path'
import { Route as CompetenciesRouteImport } from './routes/competencies'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as LabEngineRouteImport } from './routes/lab-engine'
import { Route as MyRunsRouteImport } from './routes/my-runs'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ArtifactsArtifactIdRouteImport } from './routes/artifacts.$artifactId'
import { Route as ExamsExamIdRouteImport } from './routes/exams.$examId'
import { Route as LabEngineLabIdRouteImport } from './routes/lab-engine.$labId'
import { Route as LabsLabIdRouteImport } from './routes/labs.$labId'
import { Route as LearnPlatformRouteImport } from './routes/learn.platform'
import { Route as LearnRoleRouteImport } from './routes/learn.role'
import { Route as LearnScenarioRouteImport } from './routes/learn.scenario'
import { Route as MyRunsRunIdRouteImport } from './routes/my-runs.$runId'
import { Route as PlatformsPlatformIdRouteImport } from './routes/platforms.$platformId'
import { Route as RolesRoleIdRouteImport } from './routes/roles.$roleId'
import { Route as ScenariosScenarioIdRouteImport } from './routes/scenarios.$scenarioId'
import { Route as ScenariosRagTicketAgentRouteImport } from './routes/scenarios.rag-ticket-agent'
import { Route as SimulatorsEnvRouteImport } from './routes/simulators.env'
import { Route as SimulatorsGoNoGoRouteImport } from './routes/simulators.go-no-go'
import { Route as SimulatorsInHouseAppRouteImport } from './routes/simulators.in-house-app'
import { Route as SimulatorsSaasOnboardingRouteImport } from './routes/simulators.saas-onboarding'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerPathRoute = CareerPathRouteImport.update({
  id: '/career-path',
  path: '/career-path',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetenciesRoute = CompetenciesRouteImport.update({
  id: '/competencies',
  path: '/competencies',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const LabEngineRoute = LabEngineRouteImport.update({
  id: '/lab-engine',
  path: '/lab-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRunsRoute = MyRunsRouteImport.update({
  id: '/my-runs',
  path: '/my-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsArtifactIdRoute = ArtifactsArtifactIdRouteImport.update({
  id: '/$artifactId',
  path: '/$artifactId',
  getParentRoute: () => ArtifactsRoute,
} as any)
const ExamsExamIdRoute = ExamsExamIdRouteImport.update({
  id: '/$examId',
  path: '/$examId',
  getParentRoute: () => ExamsRoute,
} as any)
const LabEngineLabIdRoute = LabEngineLabIdRouteImport.update({
  id: '/$labId',
  path: '/$labId',
  getParentRoute: () => LabEngineRoute,
} as any)
const LabsLabIdRoute = LabsLabIdRouteImport.update({
  id: '/labs/$labId',
  path: '/labs/$labId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPlatformRoute = LearnPlatformRouteImport.update({
  id: '/learn/platform',
  path: '/learn/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoleRoute = LearnRoleRouteImport.update({
  id: '/learn/role',
  path: '/learn/role',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnScenarioRoute = LearnScenarioRouteImport.update({
  id: '/learn/scenario',
  path: '/learn/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRunsRunIdRoute = MyRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => MyRunsRoute,
} as any)
const PlatformsPlatformIdRoute = PlatformsPlatformIdRouteImport.update({
  id: '/platforms/$platformId',
  path: '/platforms/$platformId',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoleIdRoute = RolesRoleIdRouteImport.update({
  id: '/roles/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosScenarioIdRoute = ScenariosScenarioIdRouteImport.update({
  id: '/scenarios/$scenarioId',
  path: '/scenarios/$scenarioId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRagTicketAgentRoute = ScenariosRagTicketAgentRouteImport.update({
  id: '/scenarios/rag-ticket-agent',
  path: '/scenarios/rag-ticket-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorsEnvRoute = SimulatorsEnvRouteImport.update({
  id: '/simulators/env',
  path: '/simulators/env',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorsGoNoGoRoute = SimulatorsGoNoGoRouteImport.update({
  id: '/simulators/go-no-go',
  path: '/simulators/go-no-go',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorsInHouseAppRoute = SimulatorsInHouseAppRouteImport.update({
  id: '/simulators/in-house-app',
  path: '/simulators/in-house-app',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorsSaasOnboardingRoute =
  SimulatorsSaasOnboardingRouteImport.update({
    id: '/simulators/saas-onboarding',
    path: '/simulators/saas-onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/auth': typeof AuthRoute
  '/career-path': typeof CareerPathRoute
  '/competencies': typeof CompetenciesRoute
  '/exams': typeof ExamsRouteWithChildren
  '/flashcards': typeof FlashcardsRoute
  '/lab-engine': typeof LabEngineRouteWithChildren
  '/my-runs': typeof MyRunsRouteWithChildren
  '/notes': typeof NotesRoute
  '/artifacts/$artifactId': typeof ArtifactsArtifactIdRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/lab-engine/$labId': typeof LabEngineLabIdRoute
  '/labs/$labId': typeof LabsLabIdRoute
  '/learn/platform': typeof LearnPlatformRoute
  '/learn/role': typeof LearnRoleRoute
  '/learn/scenario': typeof LearnScenarioRoute
  '/my-runs/$runId': typeof MyRunsRunIdRoute
  '/platforms/$platformId': typeof PlatformsPlatformIdRoute
  '/roles/$roleId': typeof RolesRoleIdRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdRoute
  '/scenarios/rag-ticket-agent': typeof ScenariosRagTicketAgentRoute
  '/simulators/env': typeof SimulatorsEnvRoute
  '/simulators/go-no-go': typeof SimulatorsGoNoGoRoute
  '/simulators/in-house-app': typeof SimulatorsInHouseAppRoute
  '/simulators/saas-onboarding': typeof SimulatorsSaasOnboardingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/auth': typeof AuthRoute
  '/career-path': typeof CareerPathRoute
  '/competencies': typeof CompetenciesRoute
  '/exams': typeof ExamsRouteWithChildren
  '/flashcards': typeof FlashcardsRoute
  '/lab-engine': typeof LabEngineRouteWithChildren
  '/my-runs': typeof MyRunsRouteWithChildren
  '/notes': typeof NotesRoute
  '/artifacts/$artifactId': typeof ArtifactsArtifactIdRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/lab-engine/$labId': typeof LabEngineLabIdRoute
  '/labs/$labId': typeof LabsLabIdRoute
  '/learn/platform': typeof LearnPlatformRoute
  '/learn/role': typeof LearnRoleRoute
  '/learn/scenario': typeof LearnScenarioRoute
  '/my-runs/$runId': typeof MyRunsRunIdRoute
  '/platforms/$platformId': typeof PlatformsPlatformIdRoute
  '/roles/$roleId': typeof RolesRoleIdRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdRoute
  '/scenarios/rag-ticket-agent': typeof ScenariosRagTicketAgentRoute
  '/simulators/env': typeof SimulatorsEnvRoute
  '/simulators/go-no-go': typeof SimulatorsGoNoGoRoute
  '/simulators/in-house-app': typeof SimulatorsInHouseAppRoute
  '/simulators/saas-onboarding': typeof SimulatorsSaasOnboardingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/auth': typeof AuthRoute
  '/career-path': typeof CareerPathRoute
  '/competencies': typeof CompetenciesRoute
  '/exams': typeof ExamsRouteWithChildren
  '/flashcards': typeof FlashcardsRoute
  '/lab-engine': typeof LabEngineRouteWithChildren
  '/my-runs': typeof MyRunsRouteWithChildren
  '/notes': typeof NotesRoute
  '/artifacts/$artifactId': typeof ArtifactsArtifactIdRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/lab-engine/$labId': typeof LabEngineLabIdRoute
  '/labs/$labId': typeof LabsLabIdRoute
  '/learn/platform': typeof LearnPlatformRoute
  '/learn/role': typeof LearnRoleRoute
  '/learn/scenario': typeof LearnScenarioRoute
  '/my-runs/$runId': typeof MyRunsRunIdRoute
  '/platforms/$platformId': typeof PlatformsPlatformIdRoute
  '/roles/$roleId': typeof RolesRoleIdRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdRoute
  '/scenarios/rag-ticket-agent': typeof ScenariosRagTicketAgentRoute
  '/simulators/env': typeof SimulatorsEnvRoute
  '/simulators/go-no-go': typeof SimulatorsGoNoGoRoute
  '/simulators/in-house-app': typeof SimulatorsInHouseAppRoute
  '/simulators/saas-onboarding': typeof SimulatorsSaasOnboardingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/auth'
    | '/career-path'
    | '/competencies'
    | '/exams'
    | '/flashcards'
    | '/lab-engine'
    | '/my-runs'
    | '/notes'
    | '/artifacts/$artifactId'
    | '/exams/$examId'
    | '/lab-engine/$labId'
    | '/labs/$labId'
    | '/learn/platform'
    | '/learn/role'
    | '/learn/scenario'
    | '/my-runs/$runId'
    | '/platforms/$platformId'
    | '/roles/$roleId'
    | '/scenarios/$scenarioId'
    | '/scenarios/rag-ticket-agent'
    | '/simulators/env'
    | '/simulators/go-no-go'
    | '/simulators/in-house-app'
    | '/simulators/saas-onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts'
    | '/auth'
    | '/career-path'
    | '/competencies'
    | '/exams'
    | '/flashcards'
    | '/lab-engine'
    | '/my-runs'
    | '/notes'
    | '/artifacts/$artifactId'
    | '/exams/$examId'
    | '/lab-engine/$labId'
    | '/labs/$labId'
    | '/learn/platform'
    | '/learn/role'
    | '/learn/scenario'
    | '/my-runs/$runId'
    | '/platforms/$platformId'
    | '/roles/$roleId'
    | '/scenarios/$scenarioId'
    | '/scenarios/rag-ticket-agent'
    | '/simulators/env'
    | '/simulators/go-no-go'
    | '/simulators/in-house-app'
    | '/simulators/saas-onboarding'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/auth'
    | '/career-path'
    | '/competencies'
    | '/exams'
    | '/flashcards'
    | '/lab-engine'
    | '/my-runs'
    | '/notes'
    | '/artifacts/$artifactId'
    | '/exams/$examId'
    | '/lab-engine/$labId'
    | '/labs/$labId'
    | '/learn/platform'
    | '/learn/role'
    | '/learn/scenario'
    | '/my-runs/$runId'
    | '/platforms/$platformId'
    | '/roles/$roleId'
    | '/scenarios/$scenarioId'
    | '/scenarios/rag-ticket-agent'
    | '/simulators/env'
    | '/simulators/go-no-go'
    | '/simulators/in-house-app'
    | '/simulators/saas-onboarding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRouteWithChildren
  AuthRoute: typeof AuthRoute
  CareerPathRoute: typeof CareerPathRoute
  CompetenciesRoute: typeof CompetenciesRoute
  ExamsRoute: typeof ExamsRouteWithChildren
  FlashcardsRoute: typeof FlashcardsRoute
  LabEngineRoute: typeof LabEngineRouteWithChildren
  MyRunsRoute: typeof MyRunsRouteWithChildren
  NotesRoute: typeof NotesRoute
  LabsLabIdRoute: typeof LabsLabIdRoute
  LearnPlatformRoute: typeof LearnPlatformRoute
  LearnRoleRoute: typeof LearnRoleRoute
  LearnScenarioRoute: typeof LearnScenarioRoute
  PlatformsPlatformIdRoute: typeof PlatformsPlatformIdRoute
  RolesRoleIdRoute: typeof RolesRoleIdRoute
  ScenariosScenarioIdRoute: typeof ScenariosScenarioIdRoute
  ScenariosRagTicketAgentRoute: typeof ScenariosRagTicketAgentRoute
  SimulatorsEnvRoute: typeof SimulatorsEnvRoute
  SimulatorsGoNoGoRoute: typeof SimulatorsGoNoGoRoute
  SimulatorsInHouseAppRoute: typeof SimulatorsInHouseAppRoute
  SimulatorsSaasOnboardingRoute: typeof SimulatorsSaasOnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-path': {
      id: '/career-path'
      path: '/career-path'
      fullPath: '/career-path'
      preLoaderRoute: typeof CareerPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competencies': {
      id: '/competencies'
      path: '/competencies'
      fullPath: '/competencies'
      preLoaderRoute: typeof CompetenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-engine': {
      id: '/lab-engine'
      path: '/lab-engine'
      fullPath: '/lab-engine'
      preLoaderRoute: typeof LabEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-runs': {
      id: '/my-runs'
      path: '/my-runs'
      fullPath: '/my-runs'
      preLoaderRoute: typeof MyRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/$artifactId': {
      id: '/artifacts/$artifactId'
      path: '/$artifactId'
      fullPath: '/artifacts/$artifactId'
      preLoaderRoute: typeof ArtifactsArtifactIdRouteImport
      parentRoute: typeof ArtifactsRoute
    }
    '/exams/$examId': {
      id: '/exams/$examId'
      path: '/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof ExamsExamIdRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/lab-engine/$labId': {
      id: '/lab-engine/$labId'
      path: '/$labId'
      fullPath: '/lab-engine/$labId'
      preLoaderRoute: typeof LabEngineLabIdRouteImport
      parentRoute: typeof LabEngineRoute
    }
    '/labs/$labId': {
      id: '/labs/$labId'
      path: '/labs/$labId'
      fullPath: '/labs/$labId'
      preLoaderRoute: typeof LabsLabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/platform': {
      id: '/learn/platform'
      path: '/learn/platform'
      fullPath: '/learn/platform'
      preLoaderRoute: typeof LearnPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/role': {
      id: '/learn/role'
      path: '/learn/role'
      fullPath: '/learn/role'
      preLoaderRoute: typeof LearnRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/scenario': {
      id: '/learn/scenario'
      path: '/learn/scenario'
      fullPath: '/learn/scenario'
      preLoaderRoute: typeof LearnScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-runs/$runId': {
      id: '/my-runs/$runId'
      path: '/$runId'
      fullPath: '/my-runs/$runId'
      preLoaderRoute: typeof MyRunsRunIdRouteImport
      parentRoute: typeof MyRunsRoute
    }
    '/platforms/$platformId': {
      id: '/platforms/$platformId'
      path: '/platforms/$platformId'
      fullPath: '/platforms/$platformId'
      preLoaderRoute: typeof PlatformsPlatformIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$roleId': {
      id: '/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/roles/$roleId'
      preLoaderRoute: typeof RolesRoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/$scenarioId': {
      id: '/scenarios/$scenarioId'
      path: '/scenarios/$scenarioId'
      fullPath: '/scenarios/$scenarioId'
      preLoaderRoute: typeof ScenariosScenarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/rag-ticket-agent': {
      id: '/scenarios/rag-ticket-agent'
      path: '/scenarios/rag-ticket-agent'
      fullPath: '/scenarios/rag-ticket-agent'
      preLoaderRoute: typeof ScenariosRagTicketAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulators/env': {
      id: '/simulators/env'
      path: '/simulators/env'
      fullPath: '/simulators/env'
      preLoaderRoute: typeof SimulatorsEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulators/go-no-go': {
      id: '/simulators/go-no-go'
      path: '/simulators/go-no-go'
      fullPath: '/simulators/go-no-go'
      preLoaderRoute: typeof SimulatorsGoNoGoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulators/in-house-app': {
      id: '/simulators/in-house-app'
      path: '/simulators/in-house-app'
      fullPath: '/simulators/in-house-app'
      preLoaderRoute: typeof SimulatorsInHouseAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulators/saas-onboarding': {
      id: '/simulators/saas-onboarding'
      path: '/simulators/saas-onboarding'
      fullPath: '/simulators/saas-onboarding'
      preLoaderRoute: typeof SimulatorsSaasOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ArtifactsRouteChildren {
  ArtifactsArtifactIdRoute: typeof ArtifactsArtifactIdRoute
}

const ArtifactsRouteChildren: ArtifactsRouteChildren = {
  ArtifactsArtifactIdRoute: ArtifactsArtifactIdRoute,
}

const ArtifactsRouteWithChildren = ArtifactsRoute._addFileChildren(
  ArtifactsRouteChildren,
)

interface ExamsRouteChildren {
  ExamsExamIdRoute: typeof ExamsExamIdRoute
}

const ExamsRouteChildren: ExamsRouteChildren = {
  ExamsExamIdRoute: ExamsExamIdRoute,
}

const ExamsRouteWithChildren = ExamsRoute._addFileChildren(ExamsRouteChildren)

interface LabEngineRouteChildren {
  LabEngineLabIdRoute: typeof LabEngineLabIdRoute
}

const LabEngineRouteChildren: LabEngineRouteChildren = {
  LabEngineLabIdRoute: LabEngineLabIdRoute,
}

const LabEngineRouteWithChildren = LabEngineRoute._addFileChildren(
  LabEngineRouteChildren,
)

interface MyRunsRouteChildren {
  MyRunsRunIdRoute: typeof MyRunsRunIdRoute
}

const MyRunsRouteChildren: MyRunsRouteChildren = {
  MyRunsRunIdRoute: MyRunsRunIdRoute,
}

const MyRunsRouteWithChildren =
  MyRunsRoute._addFileChildren(MyRunsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRouteWithChildren,
  AuthRoute: AuthRoute,
  CareerPathRoute: CareerPathRoute,
  CompetenciesRoute: CompetenciesRoute,
  ExamsRoute: ExamsRouteWithChildren,
  FlashcardsRoute: FlashcardsRoute,
  LabEngineRoute: LabEngineRouteWithChildren,
  MyRunsRoute: MyRunsRouteWithChildren,
  NotesRoute: NotesRoute,
  LabsLabIdRoute: LabsLabIdRoute,
  LearnPlatformRoute: LearnPlatformRoute,
  LearnRoleRoute: LearnRoleRoute,
  LearnScenarioRoute: LearnScenarioRoute,
  PlatformsPlatformIdRoute: PlatformsPlatformIdRoute,
  RolesRoleIdRoute: RolesRoleIdRoute,
  ScenariosScenarioIdRoute: ScenariosScenarioIdRoute,
  ScenariosRagTicketAgentRoute: ScenariosRagTicketAgentRoute,
  SimulatorsEnvRoute: SimulatorsEnvRoute,
  SimulatorsGoNoGoRoute: SimulatorsGoNoGoRoute,
  SimulatorsInHouseAppRoute: SimulatorsInHouseAppRoute,
  SimulatorsSaasOnboardingRoute: SimulatorsSaasOnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
